//! Minimal OpenType CFF/Type2 outline loading.
//!
//! This covers the simple, non-CID CFF table shape generated by the compact
//! public parity fixtures: Top DICT `CharStrings` plus direct Type2 path
//! operators without subroutines.

use crate::error::FontError;
use crate::font::Type1FontInfo;
use crate::tt::glyf::{GlyphOutline, OutlinePoint};

const TYPE2_TAG_ON: u8 = 0x01;
const TYPE2_TAG_CUBIC: u8 = 0x02;
const CFF_MAX_OPERANDS: usize = 48;
const CFF_FIXED_ONE: i32 = 1 << 16;

#[derive(Clone, Copy)]
struct DictNumber {
    integer: i32,
    fixed: i32,
}

impl DictNumber {
    fn from_integer(integer: i32) -> Self {
        // Match cff_parse_fixed for integer operands: CFF fixed fields use
        // 16.16 values and clamp outside the signed 15-bit input range.
        let fixed = if integer > 0x7FFF {
            i32::MAX
        } else if integer < -0x7FFF {
            -i32::MAX
        } else {
            integer << 16
        };
        Self { integer, fixed }
    }

    fn from_fixed(fixed: i32) -> Self {
        Self {
            integer: fixed >> 16,
            fixed,
        }
    }
}

#[derive(Debug, Clone)]
pub struct CffTable {
    charstrings: Vec<Vec<u8>>,
    font_info: Type1FontInfo,
    cid_info: Option<CffCidInfo>,
}

#[derive(Debug, Clone)]
pub struct Cff2Table {
    charstrings: Vec<Vec<u8>>,
}

#[derive(Debug, Clone)]
pub struct CffCidInfo {
    // FreeType keeps a CID face usable when a custom ROS SID is outside the
    // String INDEX; the corresponding public string pointer is then null.
    registry: Option<String>,
    ordering: Option<String>,
    supplement: i32,
    glyph_cids: Vec<u16>,
}

pub fn parse_cff(data: &[u8]) -> Result<CffTable, FontError> {
    if data.len() < 4 {
        // FreeType 2.14.3 rejects malformed OpenType CFF table framing as
        // `FT_Err_Invalid_Table` during face open (`cffload.c` INDEX/header
        // loading), before a face is exposed.
        return Err(FontError::InvalidTable("CFF: header too short".into()));
    }
    let header_size = usize::from(data[2]);
    let mut pos = header_size;
    let (_, next) = read_index(data, pos)?;
    pos = next;
    let (top_dict_index, next) = read_index(data, pos)?;
    pos = next;
    let top_dict = top_dict_index
        .first()
        .ok_or_else(|| FontError::InvalidFont("CFF: missing Top DICT".into()))?;
    let (strings, next) = read_index(data, pos)?;
    pos = next;
    let (_, _) = read_index(data, pos)?;

    let top = parse_top_dict(top_dict)?;
    let charstrings_offset = top.charstrings_offset.ok_or_else(|| {
        if top.consumed_non_charstrings_operands {
            // Pinned FreeType 2.14.3 (`cffparse.c`, `cffload.c`) reports
            // Invalid_Table when a Top DICT contains parsed non-CharStrings
            // operands but still lacks the required CharStrings offset.
            FontError::InvalidTable("CFF: missing CharStrings offset".into())
        } else {
            // Empty/minimal Top DICT shapes and CharStrings operand underflow
            // preserve the historical public Invalid_Argument classification.
            FontError::InvalidArgument("CFF: missing CharStrings offset".into())
        }
    })?;
    let (charstrings, _) = read_index(data, charstrings_offset)?;
    let font_info = top.font_info(&strings);
    let cid_info = top.cid_info(data, &strings, charstrings.len())?;
    Ok(CffTable {
        charstrings: charstrings.into_iter().map(<[u8]>::to_vec).collect(),
        font_info,
        cid_info,
    })
}

pub fn parse_cff2(data: &[u8]) -> Result<Cff2Table, FontError> {
    let header = data
        .get(..5)
        .ok_or_else(|| FontError::InvalidTable("CFF2: header too short".into()))?;
    if header[0] != 2 {
        // FreeType's CFF loader treats a non-CFF2 header as a driver-format
        // probe failure (`cffload.c:cff_font_load`), which is exposed through
        // face open as `FT_Err_Unknown_File_Format`.
        return Err(FontError::UnknownFileFormat(
            "CFF2: unsupported major version".into(),
        ));
    }
    let header_size = usize::from(header[2]);
    if header_size < 5 {
        return Err(FontError::UnknownFileFormat(
            "CFF2: invalid header size".into(),
        ));
    }
    let top_dict_length = usize::from(u16::from_be_bytes([header[3], header[4]]));
    let top_dict_end = header_size
        .checked_add(top_dict_length)
        .ok_or_else(|| FontError::InvalidTable("CFF2: Top DICT overflow".into()))?;
    let top_dict = data
        .get(header_size..top_dict_end)
        .ok_or_else(|| FontError::UnknownFileFormat("CFF2: Top DICT truncated".into()))?;
    let top = parse_top_dict(top_dict)?;
    let charstrings_offset = top
        .charstrings_offset
        .ok_or_else(|| FontError::InvalidTable("CFF2: missing CharStrings offset".into()))?;

    // CFF2 places the Global Subr INDEX immediately after the Top DICT and
    // uses a four-byte INDEX count.  Validate it even though this compact
    // decoder does not yet execute subroutines.
    let (_, _) = read_cff2_index(data, top_dict_end).map_err(map_cff2_global_index_error)?;
    let (charstrings, _) = read_cff2_index(data, charstrings_offset)?;
    Ok(Cff2Table {
        charstrings: charstrings.into_iter().map(<[u8]>::to_vec).collect(),
    })
}

fn map_cff2_global_index_error(error: FontError) -> FontError {
    match error {
        FontError::InvalidTable(message)
            if message == "CFF2: INDEX count overflow"
                || message == "CFF2: INDEX offsets out of order"
                || message == "CFF2: INDEX object overflow" =>
        {
            // The pinned C loader does not expose these global-index read
            // failures as Invalid_Table.  Its subsequent stream/index probe
            // returns Unknown_File_Format at the public face-open boundary.
            FontError::UnknownFileFormat(message)
        }
        other => other,
    }
}

impl CffTable {
    pub(crate) fn font_info(&self) -> &Type1FontInfo {
        &self.font_info
    }

    pub(crate) fn cid_info(&self) -> Option<&CffCidInfo> {
        self.cid_info.as_ref()
    }

    pub(crate) fn is_cid_keyed(&self) -> bool {
        self.cid_info.is_some()
    }

    pub fn load_glyph(&self, glyph_index: u16) -> Result<GlyphOutline, FontError> {
        let charstring = self
            .charstrings
            .get(usize::from(glyph_index))
            // FreeType 2.14.3's `cff_slot_load` returns Invalid_Argument for a
            // CharStrings index outside `num_glyphs` (`cffgload.c`).
            .ok_or_else(|| FontError::InvalidArgument("CFF: glyph index out of range".into()))?;
        Type2Decoder::new(charstring).decode()
    }
}

impl Cff2Table {
    pub fn load_glyph(&self, glyph_index: u16) -> Result<GlyphOutline, FontError> {
        let charstring = self
            .charstrings
            .get(usize::from(glyph_index))
            .ok_or_else(|| FontError::InvalidArgument("CFF2: glyph index out of range".into()))?;
        // CFF2 removes the CFF1 `endchar` operator.  The shared Type2
        // interpreter uses that operator as its contour-finalization event,
        // so add an internal sentinel without altering the stored bytes.
        let mut terminated = charstring.clone();
        terminated.push(14);
        Type2Decoder::new(&terminated).decode()
    }
}

impl CffCidInfo {
    pub(crate) fn registry(&self) -> Option<&str> {
        self.registry.as_deref()
    }

    pub(crate) fn ordering(&self) -> Option<&str> {
        self.ordering.as_deref()
    }

    pub(crate) fn supplement(&self) -> i32 {
        self.supplement
    }

    pub(crate) fn cid_for_glyph_index(&self, glyph_index: u32) -> Option<u16> {
        self.glyph_cids
            .get(usize::try_from(glyph_index).ok()?)
            .copied()
    }
}

struct TopDict {
    charstrings_offset: Option<usize>,
    consumed_non_charstrings_operands: bool,
    version_sid: Option<u16>,
    notice_sid: Option<u16>,
    full_name_sid: Option<u16>,
    family_name_sid: Option<u16>,
    weight_sid: Option<u16>,
    italic_angle: i32,
    is_fixed_pitch: bool,
    underline_position: i16,
    underline_thickness: u16,
    charset_offset: Option<usize>,
    cid_registry_sid: Option<u16>,
    cid_ordering_sid: Option<u16>,
    cid_supplement: Option<i32>,
}

impl Default for TopDict {
    fn default() -> Self {
        Self {
            charstrings_offset: None,
            consumed_non_charstrings_operands: false,
            version_sid: None,
            notice_sid: None,
            full_name_sid: None,
            family_name_sid: None,
            weight_sid: None,
            italic_angle: 0,
            is_fixed_pitch: false,
            // FreeType initializes CFF top dict defaults in
            // `src/cff/cffload.c:cff_subfont_load` before parsing the Top DICT.
            underline_position: -100,
            underline_thickness: 50,
            charset_offset: None,
            cid_registry_sid: None,
            cid_ordering_sid: None,
            cid_supplement: None,
        }
    }
}

impl TopDict {
    fn font_info(&self, strings: &[&[u8]]) -> Type1FontInfo {
        Type1FontInfo {
            version: self.version_sid.and_then(|sid| sid_string(sid, strings)),
            notice: self.notice_sid.and_then(|sid| sid_string(sid, strings)),
            full_name: self.full_name_sid.and_then(|sid| sid_string(sid, strings)),
            family_name: self
                .family_name_sid
                .and_then(|sid| sid_string(sid, strings)),
            weight: self.weight_sid.and_then(|sid| sid_string(sid, strings)),
            italic_angle: self.italic_angle,
            is_fixed_pitch: self.is_fixed_pitch,
            underline_position: self.underline_position,
            underline_thickness: self.underline_thickness,
        }
    }

    fn cid_info(
        &self,
        data: &[u8],
        strings: &[&[u8]],
        glyph_count: usize,
    ) -> Result<Option<CffCidInfo>, FontError> {
        let Some(registry_sid) = self.cid_registry_sid else {
            return Ok(None);
        };
        let Some(ordering_sid) = self.cid_ordering_sid else {
            return Ok(None);
        };
        // CFF uses 0xFFFF as the absent CID registry sentinel.  Any other
        // registry SID keeps the CID service active, even when its custom
        // String INDEX entry cannot be resolved. `cff_get_ros` returns OK
        // and exposes null for each unresolved string pointer.
        if registry_sid == 0xFFFF {
            return Ok(None);
        }
        let registry = sid_string(registry_sid, strings);
        let ordering = sid_string(ordering_sid, strings);
        let glyph_cids = parse_cff_charset_cids(data, self.charset_offset, glyph_count)?;
        Ok(Some(CffCidInfo {
            registry,
            ordering,
            supplement: self.cid_supplement.unwrap_or(0),
            glyph_cids,
        }))
    }
}

fn parse_top_dict(data: &[u8]) -> Result<TopDict, FontError> {
    let mut pos = 0usize;
    let mut stack: Vec<DictNumber> = Vec::new();
    let mut dict = TopDict::default();
    while pos < data.len() {
        let byte = data[pos];
        if byte <= 21 {
            pos += 1;
            let op = if byte == 12 {
                let escaped = *data.get(pos).ok_or_else(|| {
                    // Pinned `cffparse.c` requires the escaped operator's
                    // second byte; a truncated escape is a public
                    // Invalid_Argument face-open failure.
                    FontError::InvalidArgument("CFF: escaped dict op overflow".into())
                })?;
                pos += 1;
                0x0C00 | u16::from(escaped)
            } else {
                u16::from(byte)
            };
            if op == 15 {
                let offset = stack.last().map(|number| number.integer).ok_or_else(|| {
                    FontError::InvalidArgument("CFF: charset operand missing".into())
                })?;
                dict.charset_offset = usize::try_from(offset).ok();
            } else if op == 17 {
                let offset = stack.last().map(|number| number.integer).ok_or_else(|| {
                    // CFF Top DICT operator 17 (`CharStrings`) consumes one
                    // operand.  Pinned `cffparse.c` reports the underflow as a
                    // public Invalid_Argument face-open failure.
                    FontError::InvalidArgument("CFF: CharStrings operand missing".into())
                })?;
                dict.charstrings_offset = usize::try_from(offset).ok();
            } else if op == 0x0C1E {
                // CFF Top DICT escaped operator 30 is `ROS`.  FreeType sets
                // `FT_FACE_FLAG_CID_KEYED` for SFNT-wrapped CFF faces when
                // these registry/ordering/supplement operands are present
                // (`src/cff/cffobjs.c`, `src/cff/cffload.c`).
                if stack.len() < 3 {
                    return Err(FontError::InvalidArgument(
                        "CFF: ROS operands missing".into(),
                    ));
                }
                dict.cid_registry_sid = u16::try_from(stack[0].integer).ok();
                dict.cid_ordering_sid = u16::try_from(stack[1].integer).ok();
                dict.cid_supplement = Some(stack[2].integer);
                dict.consumed_non_charstrings_operands = true;
            } else if matches!(op, 0..=4) {
                let sid = stack
                    .last()
                    .and_then(|value| u16::try_from(value.integer).ok());
                match op {
                    0 => dict.version_sid = sid,
                    1 => dict.notice_sid = sid,
                    2 => dict.full_name_sid = sid,
                    3 => dict.family_name_sid = sid,
                    4 => dict.weight_sid = sid,
                    _ => {}
                }
                dict.consumed_non_charstrings_operands = true;
            } else if matches!(op, 0x0C01..=0x0C04) {
                let value = stack
                    .last()
                    .copied()
                    .unwrap_or_else(|| DictNumber::from_integer(0));
                match op {
                    0x0C01 => dict.is_fixed_pitch = value.integer != 0,
                    // CFF_FIELD_FIXED invokes cff_parse_fixed, so an
                    // integer operand is returned as 16.16, unlike the
                    // integer-valued underline fields beside it.
                    0x0C02 => dict.italic_angle = value.fixed,
                    0x0C03 => {
                        dict.underline_position =
                            i16::try_from(value.integer).unwrap_or_else(|_| {
                                if value.integer.is_negative() {
                                    i16::MIN
                                } else {
                                    i16::MAX
                                }
                            });
                    }
                    0x0C04 => {
                        dict.underline_thickness =
                            u16::try_from(value.integer.max(0)).unwrap_or(u16::MAX);
                    }
                    _ => {}
                }
                dict.consumed_non_charstrings_operands = true;
            } else if !stack.is_empty() {
                dict.consumed_non_charstrings_operands = true;
            }
            stack.clear();
        } else {
            let (number, next) = read_dict_number(data, pos)?;
            stack.push(number);
            pos = next;
        }
    }
    Ok(dict)
}

fn parse_cff_charset_cids(
    data: &[u8],
    charset_offset: Option<usize>,
    glyph_count: usize,
) -> Result<Vec<u16>, FontError> {
    let mut cids = Vec::with_capacity(glyph_count);
    if glyph_count == 0 {
        return Ok(cids);
    }
    // CFF charsets omit glyph 0 (`.notdef`).  FreeType reports CID 0 for GID
    // 0 through `cff_get_cid_from_glyph_index`.
    cids.push(0);
    if glyph_count == 1 {
        return Ok(cids);
    }
    let Some(offset) = charset_offset else {
        return Err(FontError::InvalidTable("CFF: CID charset missing".into()));
    };
    // ISOAdobe, Expert, and ExpertSubset are name-keyed predefined charsets.
    // They are not valid CID mappings for the ROS route.
    if let 0..=2 = offset {
        return Err(FontError::InvalidTable(
            "CFF: predefined charset cannot supply CID mapping".into(),
        ));
    }
    let format = *data
        .get(offset)
        .ok_or_else(|| FontError::InvalidTable("CFF: charset format missing".into()))?;
    let mut cursor = offset + 1;
    while cids.len() < glyph_count {
        match format {
            0 => {
                let cid = read_u16(data, cursor, "CFF: charset format 0 CID overflow")?;
                cursor += 2;
                cids.push(cid);
            }
            1 => {
                let first = read_u16(data, cursor, "CFF: charset format 1 first CID overflow")?;
                let n_left = u16::from(*data.get(cursor + 2).ok_or_else(|| {
                    FontError::InvalidTable("CFF: charset format 1 range overflow".into())
                })?);
                cursor += 3;
                push_charset_range(&mut cids, glyph_count, first, n_left)?;
            }
            2 => {
                let first = read_u16(data, cursor, "CFF: charset format 2 first CID overflow")?;
                let n_left = read_u16(data, cursor + 2, "CFF: charset format 2 range overflow")?;
                cursor += 4;
                push_charset_range(&mut cids, glyph_count, first, n_left)?;
            }
            _ => {
                return Err(FontError::InvalidTable(
                    "CFF: unsupported charset format".into(),
                ));
            }
        }
    }
    Ok(cids)
}

fn push_charset_range(
    cids: &mut Vec<u16>,
    glyph_count: usize,
    first: u16,
    n_left: u16,
) -> Result<(), FontError> {
    for delta in 0..=n_left {
        if cids.len() == glyph_count {
            break;
        }
        cids.push(
            first
                .checked_add(delta)
                .ok_or_else(|| FontError::InvalidTable("CFF: charset CID range overflow".into()))?,
        );
    }
    Ok(())
}

fn read_u16(data: &[u8], pos: usize, context: &str) -> Result<u16, FontError> {
    let bytes = data
        .get(pos..pos + 2)
        .ok_or_else(|| FontError::InvalidTable(context.into()))?;
    Ok(u16::from_be_bytes([bytes[0], bytes[1]]))
}

// CFF standard strings are part of the format, not an implementation-defined
// subset.  Keep the table in SID order so every standard Top DICT and ROS
// string has the same face-owned value as pinned FreeType.
const CFF_STANDARD_STRINGS: [&str; 391] = [
    ".notdef",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quoteright",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "quoteleft",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    "exclamdown",
    "cent",
    "sterling",
    "fraction",
    "yen",
    "florin",
    "section",
    "currency",
    "quotesingle",
    "quotedblleft",
    "guillemotleft",
    "guilsinglleft",
    "guilsinglright",
    "fi",
    "fl",
    "endash",
    "dagger",
    "daggerdbl",
    "periodcentered",
    "paragraph",
    "bullet",
    "quotesinglbase",
    "quotedblbase",
    "quotedblright",
    "guillemotright",
    "ellipsis",
    "perthousand",
    "questiondown",
    "grave",
    "acute",
    "circumflex",
    "tilde",
    "macron",
    "breve",
    "dotaccent",
    "dieresis",
    "ring",
    "cedilla",
    "hungarumlaut",
    "ogonek",
    "caron",
    "emdash",
    "AE",
    "ordfeminine",
    "Lslash",
    "Oslash",
    "OE",
    "ordmasculine",
    "ae",
    "dotlessi",
    "lslash",
    "oslash",
    "oe",
    "germandbls",
    "onesuperior",
    "logicalnot",
    "mu",
    "trademark",
    "Eth",
    "onehalf",
    "plusminus",
    "Thorn",
    "onequarter",
    "divide",
    "brokenbar",
    "degree",
    "thorn",
    "threequarters",
    "twosuperior",
    "registered",
    "minus",
    "eth",
    "multiply",
    "threesuperior",
    "copyright",
    "Aacute",
    "Acircumflex",
    "Adieresis",
    "Agrave",
    "Aring",
    "Atilde",
    "Ccedilla",
    "Eacute",
    "Ecircumflex",
    "Edieresis",
    "Egrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Igrave",
    "Ntilde",
    "Oacute",
    "Ocircumflex",
    "Odieresis",
    "Ograve",
    "Otilde",
    "Scaron",
    "Uacute",
    "Ucircumflex",
    "Udieresis",
    "Ugrave",
    "Yacute",
    "Ydieresis",
    "Zcaron",
    "aacute",
    "acircumflex",
    "adieresis",
    "agrave",
    "aring",
    "atilde",
    "ccedilla",
    "eacute",
    "ecircumflex",
    "edieresis",
    "egrave",
    "iacute",
    "icircumflex",
    "idieresis",
    "igrave",
    "ntilde",
    "oacute",
    "ocircumflex",
    "odieresis",
    "ograve",
    "otilde",
    "scaron",
    "uacute",
    "ucircumflex",
    "udieresis",
    "ugrave",
    "yacute",
    "ydieresis",
    "zcaron",
    "exclamsmall",
    "Hungarumlautsmall",
    "dollaroldstyle",
    "dollarsuperior",
    "ampersandsmall",
    "Acutesmall",
    "parenleftsuperior",
    "parenrightsuperior",
    "twodotenleader",
    "onedotenleader",
    "zerooldstyle",
    "oneoldstyle",
    "twooldstyle",
    "threeoldstyle",
    "fouroldstyle",
    "fiveoldstyle",
    "sixoldstyle",
    "sevenoldstyle",
    "eightoldstyle",
    "nineoldstyle",
    "commasuperior",
    "threequartersemdash",
    "periodsuperior",
    "questionsmall",
    "asuperior",
    "bsuperior",
    "centsuperior",
    "dsuperior",
    "esuperior",
    "isuperior",
    "lsuperior",
    "msuperior",
    "nsuperior",
    "osuperior",
    "rsuperior",
    "ssuperior",
    "tsuperior",
    "ff",
    "ffi",
    "ffl",
    "parenleftinferior",
    "parenrightinferior",
    "Circumflexsmall",
    "hyphensuperior",
    "Gravesmall",
    "Asmall",
    "Bsmall",
    "Csmall",
    "Dsmall",
    "Esmall",
    "Fsmall",
    "Gsmall",
    "Hsmall",
    "Ismall",
    "Jsmall",
    "Ksmall",
    "Lsmall",
    "Msmall",
    "Nsmall",
    "Osmall",
    "Psmall",
    "Qsmall",
    "Rsmall",
    "Ssmall",
    "Tsmall",
    "Usmall",
    "Vsmall",
    "Wsmall",
    "Xsmall",
    "Ysmall",
    "Zsmall",
    "colonmonetary",
    "onefitted",
    "rupiah",
    "Tildesmall",
    "exclamdownsmall",
    "centoldstyle",
    "Lslashsmall",
    "Scaronsmall",
    "Zcaronsmall",
    "Dieresissmall",
    "Brevesmall",
    "Caronsmall",
    "Dotaccentsmall",
    "Macronsmall",
    "figuredash",
    "hypheninferior",
    "Ogoneksmall",
    "Ringsmall",
    "Cedillasmall",
    "questiondownsmall",
    "oneeighth",
    "threeeighths",
    "fiveeighths",
    "seveneighths",
    "onethird",
    "twothirds",
    "zerosuperior",
    "foursuperior",
    "fivesuperior",
    "sixsuperior",
    "sevensuperior",
    "eightsuperior",
    "ninesuperior",
    "zeroinferior",
    "oneinferior",
    "twoinferior",
    "threeinferior",
    "fourinferior",
    "fiveinferior",
    "sixinferior",
    "seveninferior",
    "eightinferior",
    "nineinferior",
    "centinferior",
    "dollarinferior",
    "periodinferior",
    "commainferior",
    "Agravesmall",
    "Aacutesmall",
    "Acircumflexsmall",
    "Atildesmall",
    "Adieresissmall",
    "Aringsmall",
    "AEsmall",
    "Ccedillasmall",
    "Egravesmall",
    "Eacutesmall",
    "Ecircumflexsmall",
    "Edieresissmall",
    "Igravesmall",
    "Iacutesmall",
    "Icircumflexsmall",
    "Idieresissmall",
    "Ethsmall",
    "Ntildesmall",
    "Ogravesmall",
    "Oacutesmall",
    "Ocircumflexsmall",
    "Otildesmall",
    "Odieresissmall",
    "OEsmall",
    "Oslashsmall",
    "Ugravesmall",
    "Uacutesmall",
    "Ucircumflexsmall",
    "Udieresissmall",
    "Yacutesmall",
    "Thornsmall",
    "Ydieresissmall",
    "001.000",
    "001.001",
    "001.002",
    "001.003",
    "Black",
    "Bold",
    "Book",
    "Light",
    "Medium",
    "Regular",
    "Roman",
    "Semibold",
];

fn sid_string(sid: u16, strings: &[&[u8]]) -> Option<String> {
    if sid == 0xFFFF {
        return None;
    }
    if let Some(value) = CFF_STANDARD_STRINGS.get(usize::from(sid)) {
        return Some((*value).to_owned());
    }
    if sid >= 391 {
        return strings
            .get(usize::from(sid - 391))
            .and_then(|bytes| std::str::from_utf8(bytes).ok())
            .map(ToOwned::to_owned);
    }
    None
}

fn read_index(data: &[u8], pos: usize) -> Result<(Vec<&[u8]>, usize), FontError> {
    let count_bytes = data
        .get(pos..pos + 2)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX count overflow".into()))?;
    let count = usize::from(u16::from_be_bytes([count_bytes[0], count_bytes[1]]));
    let mut cursor = pos + 2;
    if count == 0 {
        return Ok((Vec::new(), cursor));
    }
    let off_size = usize::from(
        *data
            .get(cursor)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offSize missing".into()))?,
    );
    cursor += 1;
    if !(1..=4).contains(&off_size) {
        // Pinned `cffload.c` classifies malformed CFF INDEX framing as
        // Invalid_Table.  Keep object-order validation below as
        // Invalid_File_Format; the oracle distinguishes that later failure.
        return Err(FontError::InvalidTable("CFF: invalid INDEX offSize".into()));
    }
    let mut offsets = Vec::with_capacity(count + 1);
    for _ in 0..=count {
        let mut value = 0usize;
        for _ in 0..off_size {
            value = (value << 8)
                | usize::from(*data.get(cursor).ok_or_else(|| {
                    // Truncated INDEX offset arrays fail while loading
                    // CFF INDEX metadata, matching FreeType's public
                    // Invalid_Table face-open status.
                    FontError::InvalidTable("CFF: INDEX offset overflow".into())
                })?);
            cursor += 1;
        }
        offsets.push(value);
    }
    let object_base = cursor;
    let mut objects = Vec::with_capacity(count);
    for pair in offsets.windows(2) {
        let start = pair[0]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        let end = pair[1]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        if end < start {
            return Err(FontError::InvalidFont(
                "CFF: INDEX offsets out of order".into(),
            ));
        }
        objects.push(
            data.get(object_base + start..object_base + end)
                .ok_or_else(|| FontError::InvalidFont("CFF: INDEX object overflow".into()))?,
        );
    }
    let last = offsets
        .last()
        .copied()
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offsets missing".into()))?
        .checked_sub(1)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
    Ok((objects, object_base + last))
}

fn read_cff2_index(data: &[u8], pos: usize) -> Result<(Vec<&[u8]>, usize), FontError> {
    let count_bytes = data
        .get(pos..pos + 4)
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX count overflow".into()))?;
    let count = usize::try_from(u32::from_be_bytes([
        count_bytes[0],
        count_bytes[1],
        count_bytes[2],
        count_bytes[3],
    ]))
    .map_err(|_| FontError::InvalidTable("CFF2: INDEX count too large".into()))?;
    let mut cursor = pos + 4;
    if count == 0 {
        return Ok((Vec::new(), cursor));
    }
    let off_size = usize::from(
        *data
            .get(cursor)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offSize missing".into()))?,
    );
    cursor += 1;
    if !(1..=4).contains(&off_size) {
        return Err(FontError::InvalidTable(
            "CFF2: invalid INDEX offSize".into(),
        ));
    }
    let mut offsets = Vec::with_capacity(count + 1);
    for _ in 0..=count {
        let mut value = 0usize;
        for _ in 0..off_size {
            value = (value << 8)
                | usize::from(*data.get(cursor).ok_or_else(|| {
                    FontError::InvalidTable("CFF2: INDEX offset overflow".into())
                })?);
            cursor += 1;
        }
        offsets.push(value);
    }
    let object_base = cursor;
    let mut objects = Vec::with_capacity(count);
    for pair in offsets.windows(2) {
        let start = pair[0]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
        let end = pair[1]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
        if end < start {
            return Err(FontError::InvalidTable(
                "CFF2: INDEX offsets out of order".into(),
            ));
        }
        objects.push(
            data.get(object_base + start..object_base + end)
                .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX object overflow".into()))?,
        );
    }
    let last = offsets
        .last()
        .copied()
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offsets missing".into()))?
        .checked_sub(1)
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
    Ok((objects, object_base + last))
}

fn read_dict_number(data: &[u8], pos: usize) -> Result<(DictNumber, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidFont("CFF: dict number overflow".into()))?;
    match byte {
        28 => {
            let bytes = data
                .get(pos + 1..pos + 3)
                .ok_or_else(|| FontError::InvalidFont("CFF: shortint overflow".into()))?;
            Ok((
                DictNumber::from_integer(i32::from(i16::from_be_bytes([bytes[0], bytes[1]]))),
                pos + 3,
            ))
        }
        29 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidFont("CFF: longint overflow".into()))?;
            Ok((
                DictNumber::from_integer(i32::from_be_bytes([
                    bytes[0], bytes[1], bytes[2], bytes[3],
                ])),
                pos + 5,
            ))
        }
        30 => read_real_number(data, pos + 1),
        32..=246 => Ok((DictNumber::from_integer(i32::from(byte) - 139), pos + 1)),
        247..=250 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                // FreeType's CFF DICT parser classifies a truncated
                // positive operand as Invalid_Table at face open.
                FontError::InvalidTable("CFF: positive number overflow".into())
            })?);
            Ok((
                DictNumber::from_integer(((i32::from(byte) - 247) * 256) + next + 108),
                pos + 2,
            ))
        }
        251..=254 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                // Match the corresponding cff_parse_integer boundary for
                // a truncated negative operand.
                FontError::InvalidTable("CFF: negative number overflow".into())
            })?);
            Ok((
                DictNumber::from_integer(-((i32::from(byte) - 251) * 256) - next - 108),
                pos + 2,
            ))
        }
        255 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidFont("CFF: fixed number overflow".into()))?;
            Ok((
                DictNumber::from_fixed(i32::from_be_bytes([
                    bytes[0], bytes[1], bytes[2], bytes[3],
                ])),
                pos + 5,
            ))
        }
        _ => {
            // FreeType rejects bytes that are neither CFF DICT operators nor
            // DICT number encodings while parsing CFF INDEX/Top DICT metadata
            // (`cffparse.c`, `cffload.c`) as the public Invalid_Table class.
            Err(FontError::InvalidTable("CFF: invalid DICT number".into()))
        }
    }
}

fn read_real_number(data: &[u8], mut pos: usize) -> Result<(DictNumber, usize), FontError> {
    let mut text = String::new();
    loop {
        let byte = *data
            .get(pos)
            .ok_or_else(|| FontError::InvalidFont("CFF: real number overflow".into()))?;
        pos += 1;
        for nibble in [byte >> 4, byte & 0x0F] {
            match nibble {
                0..=9 => text.push(char::from(b'0' + nibble)),
                0xA => text.push('.'),
                0xB | 0xC => text.push('E'),
                0xE => text.push('-'),
                0xF => {
                    let parsed = text.parse::<f64>().unwrap_or(0.0);
                    let scaled = parsed * f64::from(CFF_FIXED_ONE);
                    let fixed = if scaled >= f64::from(i32::MAX) {
                        i32::MAX
                    } else if scaled <= -f64::from(i32::MAX) {
                        -i32::MAX
                    } else {
                        scaled.round() as i32
                    };
                    return Ok((DictNumber::from_fixed(fixed), pos));
                }
                _ => {}
            }
        }
    }
}

struct Type2Decoder<'a> {
    data: &'a [u8],
    pos: usize,
    stack: Vec<i32>,
    x: i32,
    y: i32,
    points: Vec<OutlinePoint>,
    end_pts: Vec<u16>,
    contour_start: Option<usize>,
    width_seen: bool,
}

impl<'a> Type2Decoder<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            pos: 0,
            stack: Vec::new(),
            x: 0,
            y: 0,
            points: Vec::new(),
            end_pts: Vec::new(),
            contour_start: None,
            width_seen: false,
        }
    }

    fn decode(mut self) -> Result<GlyphOutline, FontError> {
        while self.pos < self.data.len() {
            let byte = self.data[self.pos];
            if byte <= 31 && byte != 28 {
                self.pos += 1;
                match byte {
                    4 => self.vmoveto()?,
                    5 => self.rlineto()?,
                    6 => self.hv_line(true)?,
                    7 => self.hv_line(false)?,
                    8 => self.rrcurveto()?,
                    14 => {
                        self.drop_endchar_width();
                        self.close_contour()?;
                        break;
                    }
                    21 => self.rmoveto()?,
                    22 => self.hmoveto()?,
                    30 => self.vhcurveto()?,
                    31 => self.hvcurveto()?,
                    12 => {
                        self.dotsection_or_unsupported_escape()?;
                    }
                    _ => {
                        return Err(FontError::InvalidOutline(format!(
                            "CFF: Type2 op {byte} unsupported"
                        )));
                    }
                }
                self.stack.clear();
            } else {
                let (number, next) = read_type2_number(self.data, self.pos)?;
                if self.stack.len() >= CFF_MAX_OPERANDS {
                    return Err(FontError::CffStackOverflow);
                }
                self.stack.push(number);
                self.pos = next;
            }
        }
        self.build_outline()
    }

    fn build_outline(self) -> Result<GlyphOutline, FontError> {
        if self.points.is_empty() {
            return Ok(GlyphOutline::default());
        }
        let mut xmin = self.points[0].x;
        let mut ymin = self.points[0].y;
        let mut xmax = self.points[0].x;
        let mut ymax = self.points[0].y;
        for point in &self.points {
            xmin = xmin.min(point.x);
            ymin = ymin.min(point.y);
            xmax = xmax.max(point.x);
            ymax = ymax.max(point.y);
        }
        let num_contours = u16::try_from(self.end_pts.len())
            .map_err(|_| FontError::InvalidOutline("CFF: too many contours".into()))?;
        Ok(GlyphOutline {
            num_contours,
            end_pts_of_contours: self.end_pts,
            points: self.points,
            unrounded_points: None,
            xmin,
            ymin,
            xmax,
            ymax,
            bbox_xmin: xmin,
            is_composite: false,
            sub_lsb: 0,
            instructions: Vec::new(),
            components: Vec::new(),
            outline_flags: 0,
            has_cubic_tags: true,
        })
    }

    fn take_width_for(&mut self, arg_count: usize) {
        if !self.width_seen && self.stack.len() > arg_count {
            self.stack.remove(0);
        }
        self.width_seen = true;
    }

    fn drop_endchar_width(&mut self) {
        if !self.width_seen && self.stack.len() == 1 {
            self.stack.clear();
        }
        self.width_seen = true;
    }

    fn move_to(&mut self, dx: i32, dy: i32) -> Result<(), FontError> {
        self.close_contour()?;
        self.x += dx;
        self.y += dy;
        self.contour_start = Some(self.points.len());
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
        Ok(())
    }

    fn close_contour(&mut self) -> Result<(), FontError> {
        if let Some(start) = self.contour_start.take() {
            // FreeType's CFF builder (`src/psaux/psobjs.c:1999-2047`)
            // removes explicit final on-curve points that duplicate the
            // contour start, then drops contours left with only one point.
            // In this decoder, both `contour_start` assignment sites
            // immediately push the start point, so `points.len() > start`.
            // The supported drawing operators always append on-curve endpoints,
            // so a final point with matching coordinates is removable.
            if self.points.len() > start + 1 {
                let first = &self.points[start];
                let last = self.points[self.points.len() - 1];
                if first.x == last.x && first.y == last.y {
                    self.points.pop();
                }
            }

            if self.points.len() == start + 1 {
                self.points.pop();
            } else {
                let end = u16::try_from(self.points.len() - 1)
                    .map_err(|_| FontError::InvalidOutline("CFF: too many points".into()))?;
                self.end_pts.push(end);
            }
        }
        Ok(())
    }

    fn line_to(&mut self, dx: i32, dy: i32) {
        self.ensure_contour_start();
        self.x += dx;
        self.y += dy;
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
    }

    fn curve_to(&mut self, dx1: i32, dy1: i32, dx2: i32, dy2: i32, dx3: i32, dy3: i32) {
        self.ensure_contour_start();
        let c1x = self.x + dx1;
        let c1y = self.y + dy1;
        let c2x = c1x + dx2;
        let c2y = c1y + dy2;
        self.x = c2x + dx3;
        self.y = c2y + dy3;
        self.points.push(OutlinePoint {
            x: c1x,
            y: c1y,
            on_curve: false,
            tag: TYPE2_TAG_CUBIC,
        });
        self.points.push(OutlinePoint {
            x: c2x,
            y: c2y,
            on_curve: false,
            tag: TYPE2_TAG_CUBIC,
        });
        self.points.push(OutlinePoint {
            x: self.x,
            y: self.y,
            on_curve: true,
            tag: TYPE2_TAG_ON,
        });
    }

    fn ensure_contour_start(&mut self) {
        if self.contour_start.is_none() {
            // FreeType's Type2 decoder starts drawing from the current point
            // if a path operator appears before an explicit moveto.
            self.contour_start = Some(self.points.len());
            self.points.push(OutlinePoint {
                x: self.x,
                y: self.y,
                on_curve: true,
                tag: TYPE2_TAG_ON,
            });
        }
    }

    fn hmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: hmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], 0)
    }

    fn vmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: vmoveto argument count".into(),
            ));
        }
        self.move_to(0, self.stack[0])
    }

    fn rmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(2);
        if self.stack.len() != 2 {
            return Err(FontError::InvalidOutline(
                "CFF: rmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], self.stack[1])
    }

    fn rlineto(&mut self) -> Result<(), FontError> {
        // Pinned FreeType's Adobe interpreter treats an empty `rlineto` as a
        // no-op.  An odd stack still fails when its final dy lookup overflows.
        if !self.stack.len().is_multiple_of(2) {
            return Err(FontError::InvalidOutline(
                "CFF: rlineto argument count".into(),
            ));
        }
        let values = self.stack.clone();
        for pair in values.chunks_exact(2) {
            self.line_to(pair[0], pair[1]);
        }
        Ok(())
    }

    fn hv_line(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        // The Adobe interpreter loops over the available stack.  Zero
        // operands therefore make hlineto/vlineto a successful no-op.
        let mut horizontal = horizontal_first;
        let values = self.stack.clone();
        for value in values {
            if horizontal {
                self.line_to(value, 0);
            } else {
                self.line_to(0, value);
            }
            horizontal = !horizontal;
        }
        self.width_seen = true;
        Ok(())
    }

    fn rrcurveto(&mut self) -> Result<(), FontError> {
        // `cf2_interpT2CharString` consumes every complete six-operand tuple
        // and silently ignores a trailing incomplete tuple, including an
        // entirely empty stack.
        let values = self.stack.clone();
        for args in values.chunks_exact(6) {
            self.curve_to(args[0], args[1], args[2], args[3], args[4], args[5]);
        }
        Ok(())
    }

    fn hvcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(true)
    }

    fn vhcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(false)
    }

    fn alternating_curve(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        // The pinned Adobe interpreter accepts only the 8n, 8n+1, 8n+4, and
        // 8n+5 shapes directly.  For all other counts it clears the second
        // low bit and skips the corresponding leading operands.
        let count = self.stack.len() & !2;
        let mut index = self.stack.len() - count;
        let mut horizontal = horizontal_first;
        while index < count {
            let args = self.stack.get(index..index + 4).ok_or_else(|| {
                FontError::InvalidOutline("CFF: hvcurveto/vhcurveto argument count".into())
            })?;
            let last_delta = count - index == 5;
            if horizontal {
                let dx1 = args[0];
                let dx2 = args[1];
                let dy2 = args[2];
                let dy3 = args[3];
                let dx3 = if last_delta {
                    *self.stack.get(index + 4).ok_or_else(|| {
                        FontError::InvalidOutline("CFF: hvcurveto/vhcurveto argument count".into())
                    })?
                } else {
                    0
                };
                self.curve_to(dx1, 0, dx2, dy2, dx3, dy3);
            } else {
                let dy1 = args[0];
                let dx2 = args[1];
                let dy2 = args[2];
                let dx3 = args[3];
                let dy3 = if last_delta {
                    *self.stack.get(index + 4).ok_or_else(|| {
                        FontError::InvalidOutline("CFF: hvcurveto/vhcurveto argument count".into())
                    })?
                } else {
                    0
                };
                self.curve_to(0, dy1, dx2, dy2, dx3, dy3);
            }
            index += usize::from(last_delta);
            index += 4;
            horizontal = !horizontal;
        }
        Ok(())
    }

    fn dotsection_or_unsupported_escape(&mut self) -> Result<(), FontError> {
        // `cf2_buf_readByte` returns zero for this top-level fixture buffer at
        // EOF, and escaped operator zero (`dotsection`) is a documented no-op
        // in the pinned Adobe interpreter.
        let escaped = self.data.get(self.pos).copied().unwrap_or(0);
        self.pos = self.pos.saturating_add(1).min(self.data.len());
        match escaped {
            0 => Ok(()),
            10 => {
                if self.stack.len() < 2 {
                    return Err(FontError::CffTooFewArguments);
                }
                let rhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                let lhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                self.stack.push(lhs.wrapping_add(rhs));
                Ok(())
            }
            _ => Err(FontError::InvalidOutline(format!(
                "CFF: escaped Type2 op {escaped} unsupported"
            ))),
        }
    }
}

fn read_type2_number(data: &[u8], pos: usize) -> Result<(i32, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidOutline("CFF: Type2 number overflow".into()))?;
    match byte {
        28 => {
            let bytes = [
                data.get(pos + 1).copied().unwrap_or(0),
                data.get(pos + 2).copied().unwrap_or(0),
            ];
            Ok((
                i32::from(i16::from_be_bytes(bytes)),
                pos.saturating_add(3).min(data.len()),
            ))
        }
        32..=246 => Ok((i32::from(byte) - 139, pos + 1)),
        247..=250 => {
            let next = i32::from(data.get(pos + 1).copied().unwrap_or(0));
            Ok((
                ((i32::from(byte) - 247) * 256) + next + 108,
                pos.saturating_add(2).min(data.len()),
            ))
        }
        251..=254 => {
            let next = i32::from(data.get(pos + 1).copied().unwrap_or(0));
            Ok((
                -((i32::from(byte) - 251) * 256) - next - 108,
                pos.saturating_add(2).min(data.len()),
            ))
        }
        255 => {
            let bytes = [
                data.get(pos + 1).copied().unwrap_or(0),
                data.get(pos + 2).copied().unwrap_or(0),
                data.get(pos + 3).copied().unwrap_or(0),
                data.get(pos + 4).copied().unwrap_or(0),
            ];
            Ok((
                i32::from_be_bytes(bytes) >> 16,
                pos.saturating_add(5).min(data.len()),
            ))
        }
        _ => Err(FontError::InvalidOutline(
            "CFF: invalid Type2 number".into(),
        )),
    }
}
