//! Minimal OpenType CFF/Type2 outline loading.
//!
//! This covers the simple, non-CID CFF table shape generated by the compact
//! public parity fixtures: Top DICT `CharStrings`, direct Type2 path operators,
//! and the bounded CFF1 global-subroutine path.

use crate::error::FontError;
use crate::font::Type1FontInfo;
use crate::tt::glyf::{CffFixedPoint, GlyphOutline, OutlinePoint};
use std::cell::Cell;

const TYPE2_TAG_ON: u8 = 0x01;
const TYPE2_TAG_CUBIC: u8 = 0x02;
const CFF_MAX_OPERANDS: usize = 48;
const CFF_FIXED_ONE: i32 = 1 << 16;
const CFF_DEFAULT_RANDOM_SEED: u32 = 987_654_321;

#[derive(Clone, Copy)]
struct DictNumber {
    integer: i32,
    fixed: i32,
}

impl DictNumber {
    fn from_integer(integer: i32) -> Self {
        // Match cff_parse_fixed for integer operands: CFF fixed fields use
        // 16.16 values and clamp outside the signed 15-bit input range.
        let fixed = if integer > 0x7FFF {
            i32::MAX
        } else if integer < -0x7FFF {
            -i32::MAX
        } else {
            integer << 16
        };
        Self { integer, fixed }
    }

    fn from_fixed(fixed: i32) -> Self {
        Self {
            integer: fixed >> 16,
            fixed,
        }
    }
}

#[derive(Debug, Clone)]
pub struct CffTable {
    charstrings: Vec<Vec<u8>>,
    global_subrs: Vec<Vec<u8>>,
    font_info: Type1FontInfo,
    cid_info: Option<CffCidInfo>,
    private_random_seed: u32,
    random: Cell<u32>,
}

#[derive(Debug, Clone)]
pub struct Cff2Table {
    charstrings: Vec<Vec<u8>>,
}

#[derive(Debug, Clone)]
pub struct CffCidInfo {
    // FreeType keeps a CID face usable when a custom ROS SID is outside the
    // String INDEX; the corresponding public string pointer is then null.
    registry: Option<String>,
    ordering: Option<String>,
    supplement: i32,
    glyph_cids: Vec<u16>,
}

pub fn parse_cff(data: &[u8]) -> Result<CffTable, FontError> {
    if data.len() < 4 {
        // FreeType 2.14.3 rejects malformed OpenType CFF table framing as
        // `FT_Err_Invalid_Table` during face open (`cffload.c` INDEX/header
        // loading), before a face is exposed.
        return Err(FontError::InvalidTable("CFF: header too short".into()));
    }
    let header_size = usize::from(data[2]);
    let mut pos = header_size;
    let (_, next) = read_index(data, pos)?;
    pos = next;
    let (top_dict_index, next) = read_index(data, pos)?;
    pos = next;
    let top_dict = top_dict_index
        .first()
        .ok_or_else(|| FontError::InvalidFont("CFF: missing Top DICT".into()))?;
    let (strings, next) = read_index(data, pos)?;
    pos = next;
    let (global_subrs, _) = read_index(data, pos)?;

    let top = parse_top_dict(top_dict)?;
    let charstrings_offset = top.charstrings_offset.ok_or_else(|| {
        if top.consumed_non_charstrings_operands {
            // Pinned FreeType 2.14.3 (`cffparse.c`, `cffload.c`) reports
            // Invalid_Table when a Top DICT contains parsed non-CharStrings
            // operands but still lacks the required CharStrings offset.
            FontError::InvalidTable("CFF: missing CharStrings offset".into())
        } else {
            // Empty/minimal Top DICT shapes and CharStrings operand underflow
            // preserve the historical public Invalid_Argument classification.
            FontError::InvalidArgument("CFF: missing CharStrings offset".into())
        }
    })?;
    let (charstrings, _) = read_index(data, charstrings_offset)?;
    let font_info = top.font_info(&strings);
    let cid_info = top.cid_info(data, &strings, charstrings.len())?;
    let private_random_seed = parse_cff_private_random_seed(data, &top)?;
    Ok(CffTable {
        charstrings: charstrings.into_iter().map(<[u8]>::to_vec).collect(),
        global_subrs: global_subrs.into_iter().map(<[u8]>::to_vec).collect(),
        font_info,
        cid_info,
        // `cff_load_private_dict` leaves the random state at zero when the
        // Top DICT has an empty Private entry.  A non-empty private dict
        // sanitizes an absent or zero initialRandomSeed to 987654321 before
        // the Adobe CFF engine starts interpreting Type2 charstrings.
        private_random_seed,
        random: Cell::new(private_random_seed),
    })
}

pub fn parse_cff2(data: &[u8]) -> Result<Cff2Table, FontError> {
    let header = data
        .get(..5)
        .ok_or_else(|| FontError::InvalidTable("CFF2: header too short".into()))?;
    if header[0] != 2 {
        // FreeType's CFF loader treats a non-CFF2 header as a driver-format
        // probe failure (`cffload.c:cff_font_load`), which is exposed through
        // face open as `FT_Err_Unknown_File_Format`.
        return Err(FontError::UnknownFileFormat(
            "CFF2: unsupported major version".into(),
        ));
    }
    let header_size = usize::from(header[2]);
    if header_size < 5 {
        return Err(FontError::UnknownFileFormat(
            "CFF2: invalid header size".into(),
        ));
    }
    let top_dict_length = usize::from(u16::from_be_bytes([header[3], header[4]]));
    let top_dict_end = header_size
        .checked_add(top_dict_length)
        .ok_or_else(|| FontError::InvalidTable("CFF2: Top DICT overflow".into()))?;
    let top_dict = data
        .get(header_size..top_dict_end)
        .ok_or_else(|| FontError::UnknownFileFormat("CFF2: Top DICT truncated".into()))?;
    let top = parse_top_dict(top_dict)?;
    let charstrings_offset = top
        .charstrings_offset
        .ok_or_else(|| FontError::InvalidTable("CFF2: missing CharStrings offset".into()))?;

    // CFF2 places the Global Subr INDEX immediately after the Top DICT and
    // uses a four-byte INDEX count.  Validate it even though this compact
    // decoder does not yet execute subroutines.
    let (_, _) = read_cff2_index(data, top_dict_end).map_err(map_cff2_global_index_error)?;
    let (charstrings, _) = read_cff2_index(data, charstrings_offset)?;
    Ok(Cff2Table {
        charstrings: charstrings.into_iter().map(<[u8]>::to_vec).collect(),
    })
}

fn map_cff2_global_index_error(error: FontError) -> FontError {
    match error {
        FontError::InvalidTable(message)
            if message == "CFF2: INDEX count overflow"
                || message == "CFF2: INDEX offsets out of order"
                || message == "CFF2: INDEX object overflow" =>
        {
            // The pinned C loader does not expose these global-index read
            // failures as Invalid_Table.  Its subsequent stream/index probe
            // returns Unknown_File_Format at the public face-open boundary.
            FontError::UnknownFileFormat(message)
        }
        other => other,
    }
}

impl CffTable {
    pub(crate) fn font_info(&self) -> &Type1FontInfo {
        &self.font_info
    }

    pub(crate) fn cid_info(&self) -> Option<&CffCidInfo> {
        self.cid_info.as_ref()
    }

    pub(crate) fn is_cid_keyed(&self) -> bool {
        self.cid_info.is_some()
    }

    pub fn load_glyph(&self, glyph_index: u16) -> Result<GlyphOutline, FontError> {
        let charstring = self
            .charstrings
            .get(usize::from(glyph_index))
            // FreeType 2.14.3's `cff_slot_load` returns Invalid_Argument for a
            // CharStrings index outside `num_glyphs` (`cffgload.c`).
            .ok_or_else(|| FontError::InvalidArgument("CFF: glyph index out of range".into()))?;
        Type2Decoder::new(charstring, Some(&self.random), &self.global_subrs).decode()
    }

    /// Set the CFF driver seed used when a face is opened.  A zero driver seed
    /// selects the parsed private dictionary's sanitized initialRandomSeed.
    /// An empty Private entry deliberately leaves that seed at zero, matching
    /// `cffload.c:1889-1890`.
    pub(crate) fn set_random_seed(&self, seed: u32) {
        self.random.set(if seed == 0 {
            self.private_random_seed
        } else {
            seed
        });
    }
}

impl Cff2Table {
    pub fn load_glyph(&self, glyph_index: u16) -> Result<GlyphOutline, FontError> {
        let charstring = self
            .charstrings
            .get(usize::from(glyph_index))
            .ok_or_else(|| FontError::InvalidArgument("CFF2: glyph index out of range".into()))?;
        // CFF2 removes the CFF1 `endchar` operator.  The shared Type2
        // interpreter uses that operator as its contour-finalization event,
        // so add an internal sentinel without altering the stored bytes.
        let mut terminated = charstring.clone();
        terminated.push(14);
        Type2Decoder::new(&terminated, None, &[]).decode()
    }
}

impl CffCidInfo {
    pub(crate) fn registry(&self) -> Option<&str> {
        self.registry.as_deref()
    }

    pub(crate) fn ordering(&self) -> Option<&str> {
        self.ordering.as_deref()
    }

    pub(crate) fn supplement(&self) -> i32 {
        self.supplement
    }

    pub(crate) fn cid_for_glyph_index(&self, glyph_index: u32) -> Option<u16> {
        self.glyph_cids
            .get(usize::try_from(glyph_index).ok()?)
            .copied()
    }
}

struct TopDict {
    charstrings_offset: Option<usize>,
    private_size: Option<usize>,
    private_offset: Option<usize>,
    consumed_non_charstrings_operands: bool,
    version_sid: Option<u16>,
    notice_sid: Option<u16>,
    full_name_sid: Option<u16>,
    family_name_sid: Option<u16>,
    weight_sid: Option<u16>,
    italic_angle: i32,
    is_fixed_pitch: bool,
    underline_position: i16,
    underline_thickness: u16,
    charset_offset: Option<usize>,
    cid_registry_sid: Option<u16>,
    cid_ordering_sid: Option<u16>,
    cid_supplement: Option<i32>,
}

impl Default for TopDict {
    fn default() -> Self {
        Self {
            charstrings_offset: None,
            private_size: None,
            private_offset: None,
            consumed_non_charstrings_operands: false,
            version_sid: None,
            notice_sid: None,
            full_name_sid: None,
            family_name_sid: None,
            weight_sid: None,
            italic_angle: 0,
            is_fixed_pitch: false,
            // FreeType initializes CFF top dict defaults in
            // `src/cff/cffload.c:cff_subfont_load` before parsing the Top DICT.
            underline_position: -100,
            underline_thickness: 50,
            charset_offset: None,
            cid_registry_sid: None,
            cid_ordering_sid: None,
            cid_supplement: None,
        }
    }
}

impl TopDict {
    fn font_info(&self, strings: &[&[u8]]) -> Type1FontInfo {
        Type1FontInfo {
            // FreeType initializes absent Top DICT string SIDs to 0xFFFF and
            // lets `cff_index_get_sid_string` turn that sentinel into a null
            // pointer. Preserve the same internal route instead of treating
            // the missing operator as an early return; the public record is
            // unchanged, while the sentinel remains part of the C contract.
            version: sid_string(self.version_sid.unwrap_or(0xFFFF), strings),
            notice: sid_string(self.notice_sid.unwrap_or(0xFFFF), strings),
            full_name: sid_string(self.full_name_sid.unwrap_or(0xFFFF), strings),
            family_name: sid_string(self.family_name_sid.unwrap_or(0xFFFF), strings),
            weight: sid_string(self.weight_sid.unwrap_or(0xFFFF), strings),
            italic_angle: self.italic_angle,
            is_fixed_pitch: self.is_fixed_pitch,
            underline_position: self.underline_position,
            underline_thickness: self.underline_thickness,
        }
    }

    fn cid_info(
        &self,
        data: &[u8],
        strings: &[&[u8]],
        glyph_count: usize,
    ) -> Result<Option<CffCidInfo>, FontError> {
        let (registry_sid, ordering_sid) = match (self.cid_registry_sid, self.cid_ordering_sid) {
            (Some(registry_sid), Some(ordering_sid)) => (registry_sid, ordering_sid),
            _ => return Ok(None),
        };
        // CFF uses 0xFFFF as the absent CID registry sentinel.  Any other
        // registry SID keeps the CID service active, even when its custom
        // String INDEX entry cannot be resolved. `cff_get_ros` returns OK
        // and exposes null for each unresolved string pointer.
        if registry_sid == 0xFFFF {
            return Ok(None);
        }
        let registry = sid_string(registry_sid, strings);
        let ordering = sid_string(ordering_sid, strings);
        let glyph_cids = parse_cff_charset_cids(data, self.charset_offset, glyph_count)?;
        Ok(Some(CffCidInfo {
            registry,
            ordering,
            supplement: self.cid_supplement.unwrap_or(0),
            glyph_cids,
        }))
    }
}

fn parse_top_dict(data: &[u8]) -> Result<TopDict, FontError> {
    let mut pos = 0usize;
    let mut stack: Vec<DictNumber> = Vec::new();
    let mut dict = TopDict::default();
    while pos < data.len() {
        let byte = data[pos];
        if byte <= 21 {
            pos += 1;
            let op = if byte == 12 {
                let escaped = *data.get(pos).ok_or_else(|| {
                    // Pinned `cffparse.c` requires the escaped operator's
                    // second byte; a truncated escape is a public
                    // Invalid_Argument face-open failure.
                    FontError::InvalidArgument("CFF: escaped dict op overflow".into())
                })?;
                pos += 1;
                0x0C00 | u16::from(escaped)
            } else {
                u16::from(byte)
            };
            if op == 15 {
                let offset = stack.last().map(|number| number.integer).ok_or_else(|| {
                    FontError::InvalidArgument("CFF: charset operand missing".into())
                })?;
                dict.charset_offset = usize::try_from(offset).ok();
            } else if op == 17 {
                let offset = stack.last().map(|number| number.integer).ok_or_else(|| {
                    // CFF Top DICT operator 17 (`CharStrings`) consumes one
                    // operand.  Pinned `cffparse.c` reports the underflow as a
                    // public Invalid_Argument face-open failure.
                    FontError::InvalidArgument("CFF: CharStrings operand missing".into())
                })?;
                dict.charstrings_offset = usize::try_from(offset).ok();
            } else if op == 18 {
                if stack.len() < 2 {
                    return Err(FontError::InvalidArgument(
                        "CFF: Private operands missing".into(),
                    ));
                }
                let size = usize::try_from(stack[0].integer).map_err(|_| {
                    FontError::InvalidFileFormat("CFF: Private size is negative".into())
                })?;
                let offset = usize::try_from(stack[1].integer).map_err(|_| {
                    FontError::InvalidFileFormat("CFF: Private offset is negative".into())
                })?;
                dict.private_size = Some(size);
                dict.private_offset = Some(offset);
                dict.consumed_non_charstrings_operands = true;
            } else if op == 0x0C1E {
                // CFF Top DICT escaped operator 30 is `ROS`.  FreeType sets
                // `FT_FACE_FLAG_CID_KEYED` for SFNT-wrapped CFF faces when
                // these registry/ordering/supplement operands are present
                // (`src/cff/cffobjs.c`, `src/cff/cffload.c`).
                if stack.len() < 3 {
                    return Err(FontError::InvalidArgument(
                        "CFF: ROS operands missing".into(),
                    ));
                }
                dict.cid_registry_sid = u16::try_from(stack[0].integer).ok();
                dict.cid_ordering_sid = u16::try_from(stack[1].integer).ok();
                dict.cid_supplement = Some(stack[2].integer);
                dict.consumed_non_charstrings_operands = true;
            } else if matches!(op, 0..=4) {
                let sid = stack
                    .last()
                    .and_then(|value| u16::try_from(value.integer).ok());
                if op == 0 {
                    dict.version_sid = sid;
                } else if op == 1 {
                    dict.notice_sid = sid;
                } else if op == 2 {
                    dict.full_name_sid = sid;
                } else if op == 3 {
                    dict.family_name_sid = sid;
                } else {
                    // The surrounding range check restricts this operator
                    // family to 0..=4, so the final member is Weight.
                    dict.weight_sid = sid;
                }
                dict.consumed_non_charstrings_operands = true;
            } else if matches!(op, 0x0C01..=0x0C04) {
                let value = stack
                    .last()
                    .copied()
                    .unwrap_or_else(|| DictNumber::from_integer(0));
                if op == 0x0C01 {
                    dict.is_fixed_pitch = value.integer != 0;
                } else if op == 0x0C02 {
                    // CFF_FIELD_FIXED invokes cff_parse_fixed, so an
                    // integer operand is returned as 16.16, unlike the
                    // integer-valued underline fields beside it.
                    dict.italic_angle = value.fixed;
                } else if op == 0x0C03 {
                    dict.underline_position = i16::try_from(value.integer).unwrap_or_else(|_| {
                        if value.integer.is_negative() {
                            i16::MIN
                        } else {
                            i16::MAX
                        }
                    });
                } else {
                    // The surrounding range check restricts this operator
                    // family to 0x0C01..=0x0C04, so the final member is
                    // UnderlineThickness.
                    dict.underline_thickness =
                        u16::try_from(value.integer.max(0)).unwrap_or(u16::MAX);
                }
                dict.consumed_non_charstrings_operands = true;
            } else if !stack.is_empty() {
                dict.consumed_non_charstrings_operands = true;
            }
            stack.clear();
        } else {
            let (number, next) = read_dict_number(data, pos)?;
            stack.push(number);
            pos = next;
        }
    }
    Ok(dict)
}

fn parse_cff_private_random_seed(data: &[u8], top: &TopDict) -> Result<u32, FontError> {
    let (Some(size), Some(offset)) = (top.private_size, top.private_offset) else {
        // CFF's zero-initialized subfont has no private dictionary state when
        // the Top DICT omits Private entirely (`cffload.c:1885-1890`).
        return Ok(0);
    };
    if size == 0 {
        // The pinned loader returns through Exit2 before it applies the
        // private-dictionary defaults for an empty Private entry.
        return Ok(0);
    }
    let end = offset
        .checked_add(size)
        .ok_or_else(|| FontError::InvalidTable("CFF: Private dictionary overflow".into()))?;
    let private = data
        .get(offset..end)
        .ok_or_else(|| FontError::InvalidTable("CFF: Private dictionary out of range".into()))?;
    let mut pos = 0usize;
    let mut stack: Vec<DictNumber> = Vec::new();
    let mut initial_random_seed = 0_i64;
    while pos < private.len() {
        let byte = private[pos];
        if byte <= 21 {
            pos += 1;
            let op = if byte == 12 {
                let escaped = *private.get(pos).ok_or_else(|| {
                    FontError::InvalidArgument("CFF: Private escaped op overflow".into())
                })?;
                pos += 1;
                0x0C00 | u16::from(escaped)
            } else {
                u16::from(byte)
            };
            if op == 0x0C13
                && let Some(value) = stack.last()
            {
                initial_random_seed = i64::from(value.integer);
            }
            stack.clear();
        } else {
            let (number, next) = read_dict_number(private, pos)?;
            stack.push(number);
            pos = next;
        }
    }
    let initial_random_seed = initial_random_seed.abs();
    if initial_random_seed == 0 {
        return Ok(CFF_DEFAULT_RANDOM_SEED);
    }
    u32::try_from(initial_random_seed)
        .map_err(|_| FontError::InvalidTable("CFF: initialRandomSeed out of range".into()))
}

fn parse_cff_charset_cids(
    data: &[u8],
    charset_offset: Option<usize>,
    glyph_count: usize,
) -> Result<Vec<u16>, FontError> {
    let mut cids = Vec::with_capacity(glyph_count);
    if glyph_count == 0 {
        return Ok(cids);
    }
    // CFF charsets omit glyph 0 (`.notdef`).  FreeType reports CID 0 for GID
    // 0 through `cff_get_cid_from_glyph_index`.
    cids.push(0);
    if glyph_count == 1 {
        return Ok(cids);
    }
    let Some(offset) = charset_offset else {
        // FreeType's CFF loader leaves the absent Top DICT charset at its
        // predefined ISOAdobe value. A CID face with this many glyphs then
        // fails `cff_charset_load` with Invalid_File_Format rather than the
        // generic Invalid_Table used by other bounded table readers.
        return Err(FontError::InvalidFileFormat(
            "CFF: CID charset missing".into(),
        ));
    };
    // ISOAdobe, Expert, and ExpertSubset are name-keyed predefined charsets.
    // They are not valid CID mappings for the ROS route.
    if let 0..=2 = offset {
        // `cff_charset_load` rejects an implicit charset that is smaller than
        // this 257-glyph CID face with FT_Err_Invalid_File_Format.
        return Err(FontError::InvalidFileFormat(
            "CFF: predefined charset cannot supply CID mapping".into(),
        ));
    }
    let format = *data
        .get(offset)
        .ok_or_else(|| FontError::InvalidTable("CFF: charset format missing".into()))?;
    let mut cursor = offset + 1;
    while cids.len() < glyph_count {
        match format {
            0 => {
                let cid = read_u16(data, cursor, "CFF: charset format 0 CID overflow")?;
                cursor += 2;
                cids.push(cid);
            }
            1 => {
                let first = read_u16(data, cursor, "CFF: charset format 1 first CID overflow")?;
                let n_left = u16::from(*data.get(cursor + 2).ok_or_else(|| {
                    // `cff_charset_load` reaches the SFNT stream limit here;
                    // the pinned CFF driver exposes that face-open probe as
                    // Unknown_File_Format rather than Invalid_Table.
                    FontError::UnknownFileFormat("CFF: charset format 1 range overflow".into())
                })?);
                cursor += 3;
                push_charset_range(&mut cids, glyph_count, first, n_left)?;
            }
            2 => {
                let first = read_u16(data, cursor, "CFF: charset format 2 first CID overflow")?;
                let n_left = read_u16(data, cursor + 2, "CFF: charset format 2 range overflow")?;
                cursor += 4;
                push_charset_range(&mut cids, glyph_count, first, n_left)?;
            }
            _ => {
                // The CFF loader's default branch returns
                // FT_Err_Invalid_File_Format for unsupported charset formats.
                return Err(FontError::InvalidFileFormat(
                    "CFF: unsupported charset format".into(),
                ));
            }
        }
    }
    Ok(cids)
}

fn push_charset_range(
    cids: &mut Vec<u16>,
    glyph_count: usize,
    first: u16,
    n_left: u16,
) -> Result<(), FontError> {
    let remaining = glyph_count.saturating_sub(cids.len());
    for delta in (0..=n_left).take(remaining) {
        cids.push(
            first
                .checked_add(delta)
                .ok_or_else(|| FontError::InvalidTable("CFF: charset CID range overflow".into()))?,
        );
    }
    Ok(())
}

fn read_u16(data: &[u8], pos: usize, context: &str) -> Result<u16, FontError> {
    let bytes = data
        .get(pos..pos + 2)
        .ok_or_else(|| FontError::InvalidTable(context.into()))?;
    Ok(u16::from_be_bytes([bytes[0], bytes[1]]))
}

// CFF standard strings are part of the format, not an implementation-defined
// subset.  Keep the table in SID order so every standard Top DICT and ROS
// string has the same face-owned value as pinned FreeType.
const CFF_STANDARD_STRINGS: [&str; 391] = [
    ".notdef",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quoteright",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "quoteleft",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    "exclamdown",
    "cent",
    "sterling",
    "fraction",
    "yen",
    "florin",
    "section",
    "currency",
    "quotesingle",
    "quotedblleft",
    "guillemotleft",
    "guilsinglleft",
    "guilsinglright",
    "fi",
    "fl",
    "endash",
    "dagger",
    "daggerdbl",
    "periodcentered",
    "paragraph",
    "bullet",
    "quotesinglbase",
    "quotedblbase",
    "quotedblright",
    "guillemotright",
    "ellipsis",
    "perthousand",
    "questiondown",
    "grave",
    "acute",
    "circumflex",
    "tilde",
    "macron",
    "breve",
    "dotaccent",
    "dieresis",
    "ring",
    "cedilla",
    "hungarumlaut",
    "ogonek",
    "caron",
    "emdash",
    "AE",
    "ordfeminine",
    "Lslash",
    "Oslash",
    "OE",
    "ordmasculine",
    "ae",
    "dotlessi",
    "lslash",
    "oslash",
    "oe",
    "germandbls",
    "onesuperior",
    "logicalnot",
    "mu",
    "trademark",
    "Eth",
    "onehalf",
    "plusminus",
    "Thorn",
    "onequarter",
    "divide",
    "brokenbar",
    "degree",
    "thorn",
    "threequarters",
    "twosuperior",
    "registered",
    "minus",
    "eth",
    "multiply",
    "threesuperior",
    "copyright",
    "Aacute",
    "Acircumflex",
    "Adieresis",
    "Agrave",
    "Aring",
    "Atilde",
    "Ccedilla",
    "Eacute",
    "Ecircumflex",
    "Edieresis",
    "Egrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Igrave",
    "Ntilde",
    "Oacute",
    "Ocircumflex",
    "Odieresis",
    "Ograve",
    "Otilde",
    "Scaron",
    "Uacute",
    "Ucircumflex",
    "Udieresis",
    "Ugrave",
    "Yacute",
    "Ydieresis",
    "Zcaron",
    "aacute",
    "acircumflex",
    "adieresis",
    "agrave",
    "aring",
    "atilde",
    "ccedilla",
    "eacute",
    "ecircumflex",
    "edieresis",
    "egrave",
    "iacute",
    "icircumflex",
    "idieresis",
    "igrave",
    "ntilde",
    "oacute",
    "ocircumflex",
    "odieresis",
    "ograve",
    "otilde",
    "scaron",
    "uacute",
    "ucircumflex",
    "udieresis",
    "ugrave",
    "yacute",
    "ydieresis",
    "zcaron",
    "exclamsmall",
    "Hungarumlautsmall",
    "dollaroldstyle",
    "dollarsuperior",
    "ampersandsmall",
    "Acutesmall",
    "parenleftsuperior",
    "parenrightsuperior",
    "twodotenleader",
    "onedotenleader",
    "zerooldstyle",
    "oneoldstyle",
    "twooldstyle",
    "threeoldstyle",
    "fouroldstyle",
    "fiveoldstyle",
    "sixoldstyle",
    "sevenoldstyle",
    "eightoldstyle",
    "nineoldstyle",
    "commasuperior",
    "threequartersemdash",
    "periodsuperior",
    "questionsmall",
    "asuperior",
    "bsuperior",
    "centsuperior",
    "dsuperior",
    "esuperior",
    "isuperior",
    "lsuperior",
    "msuperior",
    "nsuperior",
    "osuperior",
    "rsuperior",
    "ssuperior",
    "tsuperior",
    "ff",
    "ffi",
    "ffl",
    "parenleftinferior",
    "parenrightinferior",
    "Circumflexsmall",
    "hyphensuperior",
    "Gravesmall",
    "Asmall",
    "Bsmall",
    "Csmall",
    "Dsmall",
    "Esmall",
    "Fsmall",
    "Gsmall",
    "Hsmall",
    "Ismall",
    "Jsmall",
    "Ksmall",
    "Lsmall",
    "Msmall",
    "Nsmall",
    "Osmall",
    "Psmall",
    "Qsmall",
    "Rsmall",
    "Ssmall",
    "Tsmall",
    "Usmall",
    "Vsmall",
    "Wsmall",
    "Xsmall",
    "Ysmall",
    "Zsmall",
    "colonmonetary",
    "onefitted",
    "rupiah",
    "Tildesmall",
    "exclamdownsmall",
    "centoldstyle",
    "Lslashsmall",
    "Scaronsmall",
    "Zcaronsmall",
    "Dieresissmall",
    "Brevesmall",
    "Caronsmall",
    "Dotaccentsmall",
    "Macronsmall",
    "figuredash",
    "hypheninferior",
    "Ogoneksmall",
    "Ringsmall",
    "Cedillasmall",
    "questiondownsmall",
    "oneeighth",
    "threeeighths",
    "fiveeighths",
    "seveneighths",
    "onethird",
    "twothirds",
    "zerosuperior",
    "foursuperior",
    "fivesuperior",
    "sixsuperior",
    "sevensuperior",
    "eightsuperior",
    "ninesuperior",
    "zeroinferior",
    "oneinferior",
    "twoinferior",
    "threeinferior",
    "fourinferior",
    "fiveinferior",
    "sixinferior",
    "seveninferior",
    "eightinferior",
    "nineinferior",
    "centinferior",
    "dollarinferior",
    "periodinferior",
    "commainferior",
    "Agravesmall",
    "Aacutesmall",
    "Acircumflexsmall",
    "Atildesmall",
    "Adieresissmall",
    "Aringsmall",
    "AEsmall",
    "Ccedillasmall",
    "Egravesmall",
    "Eacutesmall",
    "Ecircumflexsmall",
    "Edieresissmall",
    "Igravesmall",
    "Iacutesmall",
    "Icircumflexsmall",
    "Idieresissmall",
    "Ethsmall",
    "Ntildesmall",
    "Ogravesmall",
    "Oacutesmall",
    "Ocircumflexsmall",
    "Otildesmall",
    "Odieresissmall",
    "OEsmall",
    "Oslashsmall",
    "Ugravesmall",
    "Uacutesmall",
    "Ucircumflexsmall",
    "Udieresissmall",
    "Yacutesmall",
    "Thornsmall",
    "Ydieresissmall",
    "001.000",
    "001.001",
    "001.002",
    "001.003",
    "Black",
    "Bold",
    "Book",
    "Light",
    "Medium",
    "Regular",
    "Roman",
    "Semibold",
];

fn sid_string(sid: u16, strings: &[&[u8]]) -> Option<String> {
    if sid == 0xFFFF {
        return None;
    }
    if sid < 391 {
        // The standard-string table is complete for every SID below the
        // custom String INDEX base, so indexing is total after the sentinel
        // check and does not introduce a second impossible `None` route.
        return Some(CFF_STANDARD_STRINGS[usize::from(sid)].to_owned());
    }
    strings
        .get(usize::from(sid - 391))
        .and_then(|bytes| std::str::from_utf8(bytes).ok())
        .map(ToOwned::to_owned)
}

fn read_index(data: &[u8], pos: usize) -> Result<(Vec<&[u8]>, usize), FontError> {
    let count_bytes = data
        .get(pos..pos + 2)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX count overflow".into()))?;
    let count = usize::from(u16::from_be_bytes([count_bytes[0], count_bytes[1]]));
    let mut cursor = pos + 2;
    if count == 0 {
        return Ok((Vec::new(), cursor));
    }
    let off_size = usize::from(
        *data
            .get(cursor)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offSize missing".into()))?,
    );
    cursor += 1;
    if !(1..=4).contains(&off_size) {
        // Pinned `cffload.c` classifies malformed CFF INDEX framing as
        // Invalid_Table.  Keep object-order validation below as
        // Invalid_File_Format; the oracle distinguishes that later failure.
        return Err(FontError::InvalidTable("CFF: invalid INDEX offSize".into()));
    }
    let mut offsets = Vec::with_capacity(count + 1);
    for _ in 0..=count {
        let mut value = 0usize;
        for _ in 0..off_size {
            value = (value << 8)
                | usize::from(*data.get(cursor).ok_or_else(|| {
                    // Truncated INDEX offset arrays fail while loading
                    // CFF INDEX metadata, matching FreeType's public
                    // Invalid_Table face-open status.
                    FontError::InvalidTable("CFF: INDEX offset overflow".into())
                })?);
            cursor += 1;
        }
        offsets.push(value);
    }
    let object_base = cursor;
    let mut objects = Vec::with_capacity(count);
    for pair in offsets.windows(2) {
        let start = pair[0]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        let end = pair[1]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
        if end < start {
            return Err(FontError::InvalidFont(
                "CFF: INDEX offsets out of order".into(),
            ));
        }
        objects.push(
            data.get(object_base + start..object_base + end)
                .ok_or_else(|| FontError::InvalidFont("CFF: INDEX object overflow".into()))?,
        );
    }
    let last = offsets
        .last()
        .copied()
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offsets missing".into()))?
        .checked_sub(1)
        .ok_or_else(|| FontError::InvalidFont("CFF: INDEX offset underflow".into()))?;
    Ok((objects, object_base + last))
}

fn read_cff2_index(data: &[u8], pos: usize) -> Result<(Vec<&[u8]>, usize), FontError> {
    let count_bytes = data
        .get(pos..pos + 4)
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX count overflow".into()))?;
    let count = usize::try_from(u32::from_be_bytes([
        count_bytes[0],
        count_bytes[1],
        count_bytes[2],
        count_bytes[3],
    ]))
    .map_err(|_| FontError::InvalidTable("CFF2: INDEX count too large".into()))?;
    let mut cursor = pos + 4;
    if count == 0 {
        return Ok((Vec::new(), cursor));
    }
    let off_size = usize::from(
        *data
            .get(cursor)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offSize missing".into()))?,
    );
    cursor += 1;
    if !(1..=4).contains(&off_size) {
        return Err(FontError::InvalidTable(
            "CFF2: invalid INDEX offSize".into(),
        ));
    }
    let mut offsets = Vec::with_capacity(count + 1);
    for _ in 0..=count {
        let mut value = 0usize;
        for _ in 0..off_size {
            value = (value << 8)
                | usize::from(*data.get(cursor).ok_or_else(|| {
                    FontError::InvalidTable("CFF2: INDEX offset overflow".into())
                })?);
            cursor += 1;
        }
        offsets.push(value);
    }
    let object_base = cursor;
    let mut objects = Vec::with_capacity(count);
    for pair in offsets.windows(2) {
        let start = pair[0]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
        let end = pair[1]
            .checked_sub(1)
            .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
        if end < start {
            return Err(FontError::InvalidTable(
                "CFF2: INDEX offsets out of order".into(),
            ));
        }
        objects.push(
            data.get(object_base + start..object_base + end)
                .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX object overflow".into()))?,
        );
    }
    let last = offsets
        .last()
        .copied()
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offsets missing".into()))?
        .checked_sub(1)
        .ok_or_else(|| FontError::InvalidTable("CFF2: INDEX offset underflow".into()))?;
    Ok((objects, object_base + last))
}

fn read_dict_number(data: &[u8], pos: usize) -> Result<(DictNumber, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidFont("CFF: dict number overflow".into()))?;
    match byte {
        28 => {
            let bytes = data
                .get(pos + 1..pos + 3)
                .ok_or_else(|| FontError::InvalidFont("CFF: shortint overflow".into()))?;
            Ok((
                DictNumber::from_integer(i32::from(i16::from_be_bytes([bytes[0], bytes[1]]))),
                pos + 3,
            ))
        }
        29 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidFont("CFF: longint overflow".into()))?;
            Ok((
                DictNumber::from_integer(i32::from_be_bytes([
                    bytes[0], bytes[1], bytes[2], bytes[3],
                ])),
                pos + 5,
            ))
        }
        30 => read_real_number(data, pos + 1),
        32..=246 => Ok((DictNumber::from_integer(i32::from(byte) - 139), pos + 1)),
        247..=250 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                // FreeType's CFF DICT parser classifies a truncated
                // positive operand as Invalid_Table at face open.
                FontError::InvalidTable("CFF: positive number overflow".into())
            })?);
            Ok((
                DictNumber::from_integer(((i32::from(byte) - 247) * 256) + next + 108),
                pos + 2,
            ))
        }
        251..=254 => {
            let next = i32::from(*data.get(pos + 1).ok_or_else(|| {
                // Match the corresponding cff_parse_integer boundary for
                // a truncated negative operand.
                FontError::InvalidTable("CFF: negative number overflow".into())
            })?);
            Ok((
                DictNumber::from_integer(-((i32::from(byte) - 251) * 256) - next - 108),
                pos + 2,
            ))
        }
        255 => {
            let bytes = data
                .get(pos + 1..pos + 5)
                .ok_or_else(|| FontError::InvalidFont("CFF: fixed number overflow".into()))?;
            Ok((
                DictNumber::from_fixed(i32::from_be_bytes([
                    bytes[0], bytes[1], bytes[2], bytes[3],
                ])),
                pos + 5,
            ))
        }
        _ => {
            // FreeType rejects bytes that are neither CFF DICT operators nor
            // DICT number encodings while parsing CFF INDEX/Top DICT metadata
            // (`cffparse.c`, `cffload.c`) as the public Invalid_Table class.
            Err(FontError::InvalidTable("CFF: invalid DICT number".into()))
        }
    }
}

fn read_real_number(data: &[u8], mut pos: usize) -> Result<(DictNumber, usize), FontError> {
    let mut text = String::new();
    loop {
        let byte = *data
            .get(pos)
            .ok_or_else(|| FontError::InvalidFont("CFF: real number overflow".into()))?;
        pos += 1;
        for nibble in [byte >> 4, byte & 0x0F] {
            match nibble {
                0..=9 => text.push(char::from(b'0' + nibble)),
                0xA => text.push('.'),
                0xB | 0xC => text.push('E'),
                0xE => text.push('-'),
                0xF => {
                    let parsed = text.parse::<f64>().unwrap_or(0.0);
                    let scaled = parsed * f64::from(CFF_FIXED_ONE);
                    let fixed = if scaled >= f64::from(i32::MAX) {
                        i32::MAX
                    } else if scaled <= -f64::from(i32::MAX) {
                        -i32::MAX
                    } else {
                        scaled.round() as i32
                    };
                    return Ok((DictNumber::from_fixed(fixed), pos));
                }
                _ => {}
            }
        }
    }
}

#[derive(Clone, Copy)]
struct Type2Operand {
    value: i32,
    fixed: bool,
}

impl Type2Operand {
    fn integer(value: i32) -> Self {
        Self {
            value,
            fixed: false,
        }
    }

    fn fixed(value: i32) -> Self {
        Self { value, fixed: true }
    }

    fn as_fixed(self) -> i32 {
        if self.fixed {
            self.value
        } else {
            self.value.wrapping_shl(16)
        }
    }

    fn add(self, other: Self) -> Self {
        if self.fixed || other.fixed {
            Self::fixed(self.as_fixed().wrapping_add(other.as_fixed()))
        } else {
            Self::integer(self.value.wrapping_add(other.value))
        }
    }

    fn mul(self, other: Self) -> Self {
        Self::fixed(crate::fixed::ft_mul_fix(self.as_fixed(), other.as_fixed()))
    }
}

struct Type2Decoder<'a> {
    data: &'a [u8],
    pos: usize,
    global_subrs: &'a [Vec<u8>],
    subr_stack: Vec<(&'a [u8], usize)>,
    stack: Vec<Type2Operand>,
    x_fixed: i32,
    y_fixed: i32,
    points: Vec<OutlinePoint>,
    cff_fixed_points: Vec<CffFixedPoint>,
    end_pts: Vec<u16>,
    contour_start: Option<usize>,
    width_seen: bool,
    random: Option<&'a Cell<u32>>,
}

impl<'a> Type2Decoder<'a> {
    fn new(data: &'a [u8], random: Option<&'a Cell<u32>>, global_subrs: &'a [Vec<u8>]) -> Self {
        Self {
            data,
            pos: 0,
            global_subrs,
            subr_stack: Vec::new(),
            stack: Vec::new(),
            x_fixed: 0,
            y_fixed: 0,
            points: Vec::new(),
            cff_fixed_points: Vec::new(),
            end_pts: Vec::new(),
            contour_start: None,
            width_seen: false,
            random,
        }
    }

    fn decode(mut self) -> Result<GlyphOutline, FontError> {
        loop {
            if self.pos >= self.data.len() {
                let Some((data, pos)) = self.subr_stack.pop() else {
                    break;
                };
                self.data = data;
                self.pos = pos;
                continue;
            }
            let byte = self.data[self.pos];
            if byte <= 31 && byte != 28 {
                self.pos += 1;
                let clear_stack = match byte {
                    4 => {
                        self.vmoveto()?;
                        true
                    }
                    5 => {
                        self.rlineto()?;
                        true
                    }
                    6 => {
                        self.hv_line(true)?;
                        true
                    }
                    7 => {
                        self.hv_line(false)?;
                        true
                    }
                    8 => {
                        self.rrcurveto()?;
                        true
                    }
                    14 => {
                        self.drop_endchar_width();
                        self.close_contour()?;
                        break;
                    }
                    11 => {
                        self.return_from_global_subr()?;
                        false
                    }
                    29 => {
                        self.call_global_subr()?;
                        false
                    }
                    21 => {
                        self.rmoveto()?;
                        true
                    }
                    22 => {
                        self.hmoveto()?;
                        true
                    }
                    30 => {
                        self.vhcurveto()?;
                        true
                    }
                    31 => {
                        self.hvcurveto()?;
                        true
                    }
                    12 => self.dotsection_or_unsupported_escape()?,
                    _ => {
                        return Err(FontError::InvalidOutline(format!(
                            "CFF: Type2 op {byte} unsupported"
                        )));
                    }
                };
                if clear_stack {
                    self.stack.clear();
                }
            } else {
                let (number, next) = read_type2_number(self.data, self.pos)?;
                if self.stack.len() >= CFF_MAX_OPERANDS {
                    return Err(FontError::CffStackOverflow);
                }
                self.stack.push(Type2Operand::integer(number));
                self.pos = next;
            }
        }
        self.build_outline()
    }

    fn build_outline(self) -> Result<GlyphOutline, FontError> {
        if self.points.is_empty() {
            return Ok(GlyphOutline::default());
        }
        let mut xmin = self.points[0].x;
        let mut ymin = self.points[0].y;
        let mut xmax = self.points[0].x;
        let mut ymax = self.points[0].y;
        for point in &self.points {
            xmin = xmin.min(point.x);
            ymin = ymin.min(point.y);
            xmax = xmax.max(point.x);
            ymax = ymax.max(point.y);
        }
        let num_contours = u16::try_from(self.end_pts.len())
            .map_err(|_| FontError::InvalidOutline("CFF: too many contours".into()))?;
        Ok(GlyphOutline {
            num_contours,
            end_pts_of_contours: self.end_pts,
            points: self.points,
            unrounded_points: None,
            cff_fixed_points: Some(self.cff_fixed_points),
            xmin,
            ymin,
            xmax,
            ymax,
            bbox_xmin: xmin,
            bbox_ymax: ymax,
            is_composite: false,
            sub_lsb: 0,
            instructions: Vec::new(),
            components: Vec::new(),
            outline_flags: 0,
            has_cubic_tags: true,
        })
    }

    fn take_width_for(&mut self, arg_count: usize) {
        if !self.width_seen && self.stack.len() > arg_count {
            self.stack.remove(0);
        }
        self.width_seen = true;
    }

    fn drop_endchar_width(&mut self) {
        if !self.width_seen && self.stack.len() == 1 {
            self.stack.clear();
        }
        self.width_seen = true;
    }

    fn move_to(&mut self, dx: Type2Operand, dy: Type2Operand) -> Result<(), FontError> {
        self.close_contour()?;
        self.x_fixed = self.x_fixed.wrapping_add(dx.as_fixed());
        self.y_fixed = self.y_fixed.wrapping_add(dy.as_fixed());
        self.contour_start = Some(self.points.len());
        self.push_point(self.x_fixed, self.y_fixed, true, TYPE2_TAG_ON);
        Ok(())
    }

    fn close_contour(&mut self) -> Result<(), FontError> {
        if let Some(start) = self.contour_start.take() {
            // FreeType's CFF builder (`src/psaux/psobjs.c:1999-2047`)
            // removes explicit final on-curve points that duplicate the
            // contour start, then drops contours left with only one point.
            // In this decoder, both `contour_start` assignment sites
            // immediately push the start point, so `points.len() > start`.
            // The supported drawing operators always append on-curve endpoints,
            // so a final point with matching coordinates is removable.
            if self.points.len() > start + 1 {
                let first = &self.points[start];
                let last = self.points[self.points.len() - 1];
                if first.x == last.x && first.y == last.y {
                    self.points.pop();
                    self.cff_fixed_points.pop();
                }
            }

            if self.points.len() == start + 1 {
                self.points.pop();
                self.cff_fixed_points.pop();
            } else {
                let end = u16::try_from(self.points.len() - 1)
                    .map_err(|_| FontError::InvalidOutline("CFF: too many points".into()))?;
                self.end_pts.push(end);
            }
        }
        Ok(())
    }

    fn line_to(&mut self, dx: Type2Operand, dy: Type2Operand) {
        self.ensure_contour_start();
        self.x_fixed = self.x_fixed.wrapping_add(dx.as_fixed());
        self.y_fixed = self.y_fixed.wrapping_add(dy.as_fixed());
        self.push_point(self.x_fixed, self.y_fixed, true, TYPE2_TAG_ON);
    }

    fn curve_to(
        &mut self,
        dx1: Type2Operand,
        dy1: Type2Operand,
        dx2: Type2Operand,
        dy2: Type2Operand,
        dx3: Type2Operand,
        dy3: Type2Operand,
    ) {
        self.ensure_contour_start();
        let c1x = self.x_fixed.wrapping_add(dx1.as_fixed());
        let c1y = self.y_fixed.wrapping_add(dy1.as_fixed());
        let c2x = c1x.wrapping_add(dx2.as_fixed());
        let c2y = c1y.wrapping_add(dy2.as_fixed());
        self.x_fixed = c2x.wrapping_add(dx3.as_fixed());
        self.y_fixed = c2y.wrapping_add(dy3.as_fixed());
        self.push_point(c1x, c1y, false, TYPE2_TAG_CUBIC);
        self.push_point(c2x, c2y, false, TYPE2_TAG_CUBIC);
        self.push_point(self.x_fixed, self.y_fixed, true, TYPE2_TAG_ON);
    }

    fn ensure_contour_start(&mut self) {
        if self.contour_start.is_none() {
            // FreeType's Type2 decoder starts drawing from the current point
            // if a path operator appears before an explicit moveto.
            self.contour_start = Some(self.points.len());
            self.push_point(self.x_fixed, self.y_fixed, true, TYPE2_TAG_ON);
        }
    }

    fn push_point(&mut self, x_fixed: i32, y_fixed: i32, on_curve: bool, tag: u8) {
        self.points.push(OutlinePoint {
            // The CFF builder stores the Adobe callback's 16.16 coordinates
            // with `>> 10`, which is a truncating conversion to 26.6.  The
            // fixed sidecar retains the pre-truncation value for hinted
            // rendering, where the Adobe scale is applied first.
            x: x_fixed >> 16,
            y: y_fixed >> 16,
            on_curve,
            tag,
        });
        self.cff_fixed_points.push(CffFixedPoint {
            x: x_fixed,
            y: y_fixed,
        });
    }

    fn hmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: hmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], Type2Operand::integer(0))
    }

    fn vmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(1);
        if self.stack.len() != 1 {
            return Err(FontError::InvalidOutline(
                "CFF: vmoveto argument count".into(),
            ));
        }
        self.move_to(Type2Operand::integer(0), self.stack[0])
    }

    fn rmoveto(&mut self) -> Result<(), FontError> {
        self.take_width_for(2);
        if self.stack.len() != 2 {
            return Err(FontError::InvalidOutline(
                "CFF: rmoveto argument count".into(),
            ));
        }
        self.move_to(self.stack[0], self.stack[1])
    }

    fn rlineto(&mut self) -> Result<(), FontError> {
        // Pinned FreeType's Adobe interpreter treats an empty `rlineto` as a
        // no-op.  An odd stack still fails when its final dy lookup overflows.
        if !self.stack.len().is_multiple_of(2) {
            return Err(FontError::InvalidOutline(
                "CFF: rlineto argument count".into(),
            ));
        }
        let values = self.stack.clone();
        for pair in values.chunks_exact(2) {
            self.line_to(pair[0], pair[1]);
        }
        Ok(())
    }

    fn hv_line(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        // The Adobe interpreter loops over the available stack.  Zero
        // operands therefore make hlineto/vlineto a successful no-op.
        let mut horizontal = horizontal_first;
        let values = self.stack.clone();
        for value in values {
            if horizontal {
                self.line_to(value, Type2Operand::integer(0));
            } else {
                self.line_to(Type2Operand::integer(0), value);
            }
            horizontal = !horizontal;
        }
        self.width_seen = true;
        Ok(())
    }

    fn rrcurveto(&mut self) -> Result<(), FontError> {
        // `cf2_interpT2CharString` consumes every complete six-operand tuple
        // and silently ignores a trailing incomplete tuple, including an
        // entirely empty stack.
        let values = self.stack.clone();
        for args in values.chunks_exact(6) {
            self.curve_to(args[0], args[1], args[2], args[3], args[4], args[5]);
        }
        Ok(())
    }

    fn hvcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(true)
    }

    fn vhcurveto(&mut self) -> Result<(), FontError> {
        self.alternating_curve(false)
    }

    fn alternating_curve(&mut self, horizontal_first: bool) -> Result<(), FontError> {
        // The pinned Adobe interpreter accepts only the 8n, 8n+1, 8n+4, and
        // 8n+5 shapes directly.  For all other counts it clears the second
        // low bit and skips the corresponding leading operands.
        let count = self.stack.len() & !2;
        let mut index = self.stack.len() - count;
        let mut horizontal = horizontal_first;
        while index < count {
            let args = self.stack.get(index..index + 4).ok_or_else(|| {
                // The Adobe CFF driver's public `cff_slot_load` boundary
                // reports a malformed alternating-curve argument list as
                // `FT_Err_Invalid_File_Format`, including through the Rust
                // API's error-preserving path.
                FontError::InvalidFileFormat("CFF: hvcurveto/vhcurveto argument count".into())
            })?;
            let last_delta = count - index == 5;
            if horizontal {
                let dx3 = if last_delta {
                    self.stack[index + 4]
                } else {
                    Type2Operand::integer(0)
                };
                self.curve_to(
                    args[0],
                    Type2Operand::integer(0),
                    args[1],
                    args[2],
                    dx3,
                    args[3],
                );
            } else {
                let dy3 = if last_delta {
                    self.stack[index + 4]
                } else {
                    Type2Operand::integer(0)
                };
                self.curve_to(
                    Type2Operand::integer(0),
                    args[0],
                    args[1],
                    args[2],
                    args[3],
                    dy3,
                );
            }
            index += usize::from(last_delta);
            index += 4;
            horizontal = !horizontal;
        }
        Ok(())
    }

    fn call_global_subr(&mut self) -> Result<(), FontError> {
        let operand = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
        if operand.fixed {
            return Err(FontError::InvalidFileFormat(
                "CFF: global subroutine operand is not an integer".into(),
            ));
        }
        let bias = cff_subroutine_bias(self.global_subrs.len());
        let index = i64::from(operand.value) + i64::from(bias);
        let Ok(index) = usize::try_from(index) else {
            return Err(FontError::InvalidFileFormat(
                "CFF: global subroutine index out of range".into(),
            ));
        };
        let Some(subr) = self.global_subrs.get(index).map(Vec::as_slice) else {
            return Err(FontError::InvalidFileFormat(
                "CFF: global subroutine index out of range".into(),
            ));
        };
        if self.subr_stack.len() >= 10 {
            return Err(FontError::InvalidFileFormat(
                "CFF: global subroutine recursion limit".into(),
            ));
        }
        self.subr_stack.push((self.data, self.pos));
        self.data = subr;
        self.pos = 0;
        Ok(())
    }

    fn return_from_global_subr(&mut self) -> Result<(), FontError> {
        let Some((data, pos)) = self.subr_stack.pop() else {
            return Err(FontError::InvalidFileFormat(
                "CFF: return outside global subroutine".into(),
            ));
        };
        self.data = data;
        self.pos = pos;
        Ok(())
    }

    fn dotsection_or_unsupported_escape(&mut self) -> Result<bool, FontError> {
        // `cf2_buf_readByte` returns zero for this top-level fixture buffer at
        // EOF, and escaped operator zero (`dotsection`) is a documented no-op
        // in the pinned Adobe interpreter.
        let escaped = self.data.get(self.pos).copied().unwrap_or(0);
        self.pos = self.pos.saturating_add(1).min(self.data.len());
        match escaped {
            0 => Ok(true),
            10 => {
                if self.stack.len() < 2 {
                    return Err(FontError::CffTooFewArguments);
                }
                let rhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                let lhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                self.stack.push(lhs.add(rhs));
                // `add` is a stack operator: its result remains available to
                // the next Type 2 operator.
                Ok(false)
            }
            24 => {
                if self.stack.len() < 2 {
                    return Err(FontError::CffTooFewArguments);
                }
                let rhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                let lhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                self.stack.push(lhs.mul(rhs));
                // `mul` is a stack operator: its result remains available to
                // the next Type 2 operator.
                Ok(false)
            }
            15 => {
                if self.stack.len() < 2 {
                    return Err(FontError::CffTooFewArguments);
                }
                let rhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                let lhs = self.stack.pop().ok_or(FontError::CffTooFewArguments)?;
                self.stack.push(Type2Operand::integer(i32::from(
                    lhs.as_fixed() == rhs.as_fixed(),
                )));
                Ok(false)
            }
            23 => {
                let Some(random) = self.random else {
                    return Err(FontError::InvalidOutline(
                        "CFF2: random operator unsupported".into(),
                    ));
                };
                let seed = random.get();
                self.stack
                    .push(Type2Operand::fixed(((seed & 0xFFFF) + 1) as i32));
                random.set(cff_random(seed));
                // `random` pushes a value for a following arithmetic or path
                // operator, so do not clear the operand stack here.
                Ok(false)
            }
            // FreeType's Adobe Type2 interpreter logs an unknown escaped
            // operator and continues as a no-op.  Treating it as a hard
            // outline error diverges from malformed public CFF inputs such
            // as `pure-cff-type2-unknown-escape-no-hinting`.
            _ => Ok(true),
        }
    }
}

fn cff_random(mut value: u32) -> u32 {
    // Pinned FreeType's psaux `cff_random` uses this 32-bit xorshift state for
    // every Type 2 `random` operator.
    value ^= value << 13;
    value ^= value >> 17;
    value ^= value << 5;
    value
}

fn cff_subroutine_bias(count: usize) -> i32 {
    if count < 1_240 {
        107
    } else if count < 33_900 {
        1_131
    } else {
        32_768
    }
}

fn read_type2_number(data: &[u8], pos: usize) -> Result<(i32, usize), FontError> {
    let byte = *data
        .get(pos)
        .ok_or_else(|| FontError::InvalidOutline("CFF: Type2 number overflow".into()))?;
    match byte {
        28 => {
            let bytes = [
                data.get(pos + 1).copied().unwrap_or(0),
                data.get(pos + 2).copied().unwrap_or(0),
            ];
            Ok((
                i32::from(i16::from_be_bytes(bytes)),
                pos.saturating_add(3).min(data.len()),
            ))
        }
        32..=246 => Ok((i32::from(byte) - 139, pos + 1)),
        247..=250 => {
            let next = i32::from(data.get(pos + 1).copied().unwrap_or(0));
            Ok((
                ((i32::from(byte) - 247) * 256) + next + 108,
                pos.saturating_add(2).min(data.len()),
            ))
        }
        251..=254 => {
            let next = i32::from(data.get(pos + 1).copied().unwrap_or(0));
            Ok((
                -((i32::from(byte) - 251) * 256) - next - 108,
                pos.saturating_add(2).min(data.len()),
            ))
        }
        255 => {
            let bytes = [
                data.get(pos + 1).copied().unwrap_or(0),
                data.get(pos + 2).copied().unwrap_or(0),
                data.get(pos + 3).copied().unwrap_or(0),
                data.get(pos + 4).copied().unwrap_or(0),
            ];
            Ok((
                i32::from_be_bytes(bytes) >> 16,
                pos.saturating_add(5).min(data.len()),
            ))
        }
        _ => Err(FontError::InvalidOutline(
            "CFF: invalid Type2 number".into(),
        )),
    }
}
