//! Native C ABI for the pure-Rust `fontdone` engine.
//!
//! This crate is consumed through the shipped C/C++ headers and its `cdylib` or
//! `staticlib` artifact. The Rust `rlib` exists for repository verification; it
//! is not an ergonomic Rust API. Rust applications should use `fontdone` or
//! `fontdone::ffi`.
//!
//! # Raw-pointer contract
//!
//! Exported `FT_*` and `FTC_*` functions retain the pinned FreeType calling
//! convention, numeric errors, record layouts, and ownership concepts. Every
//! non-null pointer must address the complete declared object for the duration
//! of the call. Pointer/length pairs must describe readable or writable memory,
//! and borrowed face/slot/table data must not outlive its documented owner.
//! Violating those C preconditions is undefined behavior even when null and
//! range errors are validated.
//!
//! The package README explains building, linking, lifecycle ordering, static
//! dependencies, installation, supported targets, and the measured
//! compatibility boundary. The shipped headers are authoritative for individual
//! signatures and field layouts.

mod implementation;

pub use implementation::*;

/// Exports the raw C entry point corresponding to FreeType's
/// `FT_Init_FreeType`.
///
/// The output pointer must be writable. On success it receives one caller-owned
/// library handle that must be released exactly once with `FT_Done_FreeType`.
pub use implementation::FT_Init_FreeType;

macro_rules! document_c_entry_points {
    ($($name:ident),+ $(,)?) => {
        $(
            #[doc = concat!("Exports the raw C ABI entry point `", stringify!($name), "`.")]
            ///
            /// C callers must follow the pointer, lifetime, mutation, and
            /// ownership contract in the shipped declaration and package guide.
            /// Rust callers should use `fontdone::ffi` instead of invoking this
            /// raw boundary.
            pub use implementation::$name;
        )+
    };
}

#[cfg(feature = "abi-test-support")]
macro_rules! document_abi_test_support {
    ($($name:ident),+ $(,)?) => {
        $(
            #[doc = concat!(
                "Exposes C-boundary verification data for `",
                stringify!($name),
                "`."
            )]
            ///
            /// This helper is available only to the maintained ABI/parity
            /// harness. It is not an exported FreeType-compatible C symbol or a
            /// downstream Rust integration API.
            pub use implementation::$name;
        )+
    };
}

document_c_entry_points!(
    FT_Bitmap_Init,
    FT_Bitmap_New,
    FT_Gzip_Uncompress,
    FT_Stream_OpenBzip2,
    FT_Stream_OpenLZW,
    FTC_Manager_New,
    FTC_Manager_Reset,
    FTC_Manager_Done,
    FTC_Manager_LookupFace,
    FTC_Manager_LookupSize,
    FTC_Manager_RemoveFaceID,
    FTC_CMapCache_New,
    FTC_CMapCache_Lookup,
    FTC_ImageCache_New,
    FTC_ImageCache_Lookup,
    FTC_ImageCache_LookupScaler,
    FTC_SBitCache_New,
    FTC_SBitCache_Lookup,
    FTC_SBitCache_LookupScaler,
    FTC_Node_Unref,
    FT_Stream_OpenGzip,
    FT_List_Add,
    FT_List_Insert,
    FT_List_Find,
    FT_List_Remove,
    FT_List_Up,
    FT_List_Iterate,
    FT_List_Finalize,
    FT_Bitmap_Copy,
    FT_Bitmap_Convert,
    FT_Bitmap_Done,
    FT_Bitmap_Embolden,
    FT_Bitmap_Blend,
    FT_Palette_Data_Get,
    FT_Palette_Select,
    FT_Palette_Set_Foreground_Color,
    FT_Get_Color_Glyph_Layer,
    FT_Get_Color_Glyph_ClipBox,
    FT_Get_Color_Glyph_Paint,
    FT_Get_Paint,
    FT_Get_Paint_Layers,
    FT_Get_Colorline_Stops,
    FT_TrueTypeGX_Free,
    FT_TrueTypeGX_Validate,
    FT_ClassicKern_Free,
    FT_ClassicKern_Validate,
    FT_Error_String,
    FT_OpenType_Validate,
    FT_Get_PS_Font_Info,
    FT_Get_PS_Font_Private,
    FT_Has_PS_Glyph_Names,
    FT_Get_PS_Font_Value,
    FT_OpenType_Free,
    FT_Done_FreeType,
    FT_New_Library,
    FT_Reference_Library,
    FT_Done_Library,
    FT_Get_MM_Var,
    FT_Done_MM_Var,
    FT_Get_Var_Axis_Flags,
    FT_Library_SetLcdFilter,
    FT_Library_SetLcdFilterWeights,
    FT_Library_SetLcdGeometry,
    FT_Get_TrueType_Engine_Type,
    FT_Property_Get,
    FT_Property_Set,
    FT_Set_Default_Properties,
    FT_Face_Properties,
    FT_Add_Default_Modules,
    FT_Add_Module,
    FT_Get_Module,
    FT_Remove_Module,
    FT_Set_Debug_Hook,
    FT_Trace_Set_Level,
    FT_Trace_Set_Default_Level,
    FT_Set_Log_Handler,
    FT_Set_Default_Log_Handler,
    FT_Get_Renderer,
    FT_Set_Renderer,
    FT_MulDiv,
    FT_MulFix,
    FT_DivFix,
    FT_RoundFix,
    FT_CeilFix,
    FT_FloorFix,
    FT_Sin,
    FT_Cos,
    FT_Tan,
    FT_Atan2,
    FT_Angle_Diff,
    FT_Vector_Unit,
    FT_Vector_Rotate,
    FT_Vector_Length,
    FT_Vector_Polarize,
    FT_Vector_From_Polar,
    FT_Vector_Transform,
    FT_Matrix_Multiply,
    FT_Matrix_Invert,
    FT_Open_Face,
    FT_New_Face,
    FT_Attach_File,
    FT_Attach_Stream,
    FT_New_Memory_Face,
    FT_Reference_Face,
    FT_Done_Face,
    FT_Face_CheckTrueTypePatents,
    FT_Face_SetUnpatentedHinting,
    FT_Outline_Get_CBox,
    FT_Glyph_Get_CBox,
    FT_Get_Glyph,
    FT_New_Glyph,
    FT_Glyph_Copy,
    FT_Done_Glyph,
    FT_Glyph_Transform,
    FT_Glyph_To_Bitmap,
    FT_Glyph_Stroke,
    FT_Glyph_StrokeBorder,
    FT_Outline_Get_BBox,
    FT_Outline_Get_Bitmap,
    FT_Outline_Render,
    FT_Outline_Decompose,
    FT_Outline_Get_Orientation,
    FT_Outline_Check,
    FT_Outline_Copy,
    FT_Outline_Embolden,
    FT_Outline_EmboldenXY,
    FT_Outline_GetInsideBorder,
    FT_Outline_GetOutsideBorder,
    FT_Stroker_New,
    FT_Stroker_Set,
    FT_Stroker_Rewind,
    FT_Stroker_BeginSubPath,
    FT_Stroker_ParseOutline,
    FT_Stroker_LineTo,
    FT_Stroker_ConicTo,
    FT_Stroker_CubicTo,
    FT_Stroker_EndSubPath,
    FT_Stroker_GetBorderCounts,
    FT_Stroker_GetCounts,
    FT_Stroker_Done,
    FT_Stroker_ExportBorder,
    FT_Stroker_Export,
    FT_Outline_New,
    FT_Outline_Done,
    FT_Outline_Reverse,
    FT_Outline_Transform,
    FT_Outline_Translate,
    FT_Set_Char_Size,
    FT_Set_Pixel_Sizes,
    FT_Set_Transform,
    FT_Get_Transform,
    FT_Request_Size,
    FT_Select_Size,
    FT_New_Size,
    FT_Activate_Size,
    FT_Done_Size,
    FT_Get_Char_Index,
    FT_Face_GetCharVariantIndex,
    FT_Face_GetCharVariantIsDefault,
    FT_Face_GetVariantSelectors,
    FT_Face_GetVariantsOfChar,
    FT_Face_GetCharsOfVariant,
    FT_Get_Kerning,
    FT_Get_PFR_Kerning,
    FT_Get_PFR_Metrics,
    FT_Get_PFR_Advance,
    FT_Select_Charmap,
    FT_Set_Charmap,
    FT_Get_Charmap_Index,
    FT_Get_CMap_Format,
    FT_Get_CMap_Language_ID,
    FT_Get_FSType_Flags,
    FT_Get_Gasp,
    FT_Get_Glyph_Name,
    FT_Get_Name_Index,
    FT_Get_Postscript_Name,
    FT_Get_Font_Format,
    FT_Get_X11_Font_Format,
    FT_Set_Named_Instance,
    FT_Set_Var_Design_Coordinates,
    FT_Get_Var_Design_Coordinates,
    FT_Get_Var_Blend_Coordinates,
    FT_Get_MM_Blend_Coordinates,
    FT_Get_Multi_Master,
    FT_Set_MM_Design_Coordinates,
    FT_Set_MM_WeightVector,
    FT_Get_MM_WeightVector,
    FT_Set_Var_Blend_Coordinates,
    FT_Set_MM_Blend_Coordinates,
    FT_Get_Default_Named_Instance,
    FT_Get_WinFNT_Header,
    FT_Get_BDF_Property,
    FT_Get_BDF_Charset_ID,
    FT_Get_CID_Is_Internally_CID_Keyed,
    FT_Get_CID_From_Glyph_Index,
    FT_Get_CID_Registry_Ordering_Supplement,
    FT_Get_Sfnt_Name_Count,
    FT_Get_Sfnt_Name,
    FT_Get_Sfnt_LangTag,
    FT_Get_Track_Kerning,
    FT_Get_Sfnt_Table,
    FT_Load_Sfnt_Table,
    FT_Sfnt_Table_Info,
    FT_Get_First_Char,
    FT_Get_Next_Char,
    FT_Library_Version,
    FT_Load_Char,
    FT_Load_Glyph,
    FT_Get_Advance,
    FT_Get_Advances,
    FT_Get_SubGlyph_Info,
    FT_Render_Glyph,
    FT_GlyphSlot_Embolden,
    FT_GlyphSlot_Own_Bitmap,
    FT_GlyphSlot_AdjustWeight,
    FT_GlyphSlot_Oblique,
    FT_GlyphSlot_Slant,
);

#[cfg(feature = "abi-test-support")]
document_abi_test_support!(
    abi_support_owned_mm_var_count,
    abi_palette_data_snapshot,
    abi_palette_select_snapshot,
    abi_palette_select_without_output,
    abi_palette_mutate_entry,
    abi_support_bzip2_stream_bytes,
    abi_support_bzip2_stream_close,
    abi_support_bzip2_stream_is_open,
    abi_support_lzw_stream_bytes,
    abi_support_lzw_stream_close,
    abi_custom_memory_lifecycle,
    abi_raster_lifecycle,
    abi_raster_new_error,
    abi_support_raster_class_probe,
    abi_raster_set_mode,
    abi_custom_glyph_lifecycle,
    abi_incremental_glyph_lifecycle,
    abi_incremental_state_lifecycle,
    abi_support_gzip_stream_bytes,
    abi_support_gzip_stream_close,
    abi_support_colr_v1_paint_layer_iterator,
    abi_support_colr_v1_paint_colorline,
    abi_support_colr_v1_paint_linear_gradient,
    abi_support_colr_v1_paint_transform,
    abi_support_colr_v1_paint_graph,
    abi_support_colr_v1_public_paint_solid,
    abi_byte_slice,
    abi_bdf_property_snapshot,
    abi_c_string_bytes,
    abi_open_type_validation_table_copy,
    abi_uint32_list,
    abi_face_info,
    abi_face_stream_info,
    abi_face_uses_stream,
    abi_external_stream_runtime,
    abi_face_available_sizes,
    abi_mm_var_descriptor,
    abi_charmap_count,
    abi_charmap_by_index,
    abi_charmap_info_by_index,
    abi_active_charmap_index,
    abi_slot_snapshot,
    abi_renderer_mode_acceptance,
    abi_get_outline_glyph_from_face,
    abi_outline_glyph_snapshot,
    abi_support_corrupt_outline_glyph_for_render_failure,
    abi_bitmap_glyph_snapshot,
    abi_svg_glyph_snapshot,
    abi_render_glyph_from_face,
    abi_sfnt_load_name_diagnostic,
    abi_truetype_context_allocation_failure_diagnostic,
    abi_get_glyph_from_face,
    abi_set_unsupported_glyph_slot,
    abi_set_malformed_get_glyph_slot,
    abi_set_outline_glyph_slot_advance,
    abi_glyphslot_slant_from_face,
    abi_glyphslot_adjust_weight_from_face,
    abi_glyphslot_embolden_from_face,
    abi_glyphslot_own_bitmap_from_face,
    abi_glyphslot_own_bitmap_copy_allocation_failure_from_face,
    abi_fvar_namedstyle_coords,
    abi_glyphslot_set_own_bitmap_from_face,
    abi_glyphslot_oblique_from_face,
    abi_get_subglyph_info_from_face,
    abi_size_metrics,
    abi_active_size,
    abi_size_rec_snapshot,
    abi_size_rec_set_generic_data,
    abi_sfnt_os2,
    abi_sfnt_vhea,
    abi_sfnt_maxp,
    abi_glyph_slot_pointer,
    abi_support_module_interface_present,
    abi_support_module_requester_service_available,
    abi_glyph_to_script_map_sample,
    abi_glyph_to_script_map_mutate,
    abi_support_set_default_properties,
    abi_face_properties_state,
    abi_support_get_module_interface,
    abi_support_new_library_without_default_modules,
    abi_support_library_has_truetype_module,
    abi_support_library_has_module,
    abi_support_library_module_flags,
    abi_support_library_module_count,
    abi_support_synthetic_module_info,
    abi_support_module_table_observation,
    abi_support_set_face_finalizer,
    abi_support_library_renderer_class,
    abi_support_library_default_module_names,
    abi_support_library_refcount,
    abi_support_library_memory_is,
    abi_support_face_memory_is,
    abi_support_library_has_truetype_engine_service,
    abi_support_debug_hook_classes,
    abi_glyph_copy_failure_cleanup,
    abi_support_outline_render_direct_spans,
    abi_support_outline_decompose_trace,
    abi_support_face_driver_name,
);
