// Generated by scripts/generate_wasm_contract.py. Do not edit.

/** Inputs accepted by the browser Wasm initializer. */
export type FontdoneWasmSource =
  | string
  | URL
  | Request
  | Response
  | BufferSource
  | WebAssembly.Module
  | WebAssembly.Instance;

/** Options used while opening copied font bytes. */
export interface OpenFaceOptions {
  /** Face or named-instance index. Must fit in a signed 64-bit integer. */
  readonly faceIndex?: number | bigint;
  /** Initial integer pixels per EM. Defaults to 16. */
  readonly pixelSize?: number;
}

/** Options for the map-load-render convenience operation. */
export interface RenderOptions {
  /** FreeType-compatible `FT_LOAD_*` bits. Defaults to `LoadFlags.DEFAULT`. */
  readonly loadFlags?: number;
  /** FreeType-compatible render mode. Defaults to `RenderMode.NORMAL`. */
  readonly renderMode?: number;
}

/** An owned copy of a rendered slot bitmap. */
export interface GlyphBitmap {
  readonly glyphIndex: number;
  readonly width: number;
  readonly height: number;
  readonly pitch: number;
  /** Raw rows with length `abs(pitch) * height`. */
  readonly pixels: Uint8Array;
}

/** One face owned by a `Fontdone` WebAssembly instance. */
export interface FontdoneFace {
  readonly closed: boolean;
  setPixelSize(size: number): this;
  setPixelSizes(pixelWidth: number, pixelHeight: number): this;
  getCharIndex(character: number | string): number;
  loadGlyph(glyphIndex: number, loadFlags?: number): this;
  renderGlyph(renderMode?: number): GlyphBitmap;
  render(character: number | string, options?: RenderOptions): GlyphBitmap;
  /** Releases the face. Repeated calls are no-ops. */
  close(): void;
}

/** An independent fontdone WebAssembly instance. */
export interface Fontdone {
  readonly closed: boolean;
  openFace(
    fontData: ArrayBuffer | ArrayBufferView,
    options?: OpenFaceOptions,
  ): FontdoneFace;
  /** Closes every owned face. Repeated calls are no-ops. */
  close(): void;
}

/** A preserved nonzero FreeType-compatible status from the Wasm engine. */
export declare class FontdoneError extends Error {
  readonly operation: string;
  readonly code: number;
  constructor(operation: string, code: number);
}

export declare const LoadFlags: Readonly<{
  DEFAULT: 0;
}>;

export declare const RenderMode: Readonly<{
  NORMAL: 0;
}>;

/**
 * Instantiates a fresh engine. With no source, fetches `fontdone.wasm`
 * relative to the package entry point.
 */
export declare function createFontdone(
  source?: FontdoneWasmSource | PromiseLike<FontdoneWasmSource>,
): Promise<Fontdone>;

export declare const init: typeof createFontdone;

export default createFontdone;
