// Generated by scripts/generate_wasm_contract.py. Do not edit.
// This is the directly callable JavaScript host subset. abi.json inventories every
// no_mangle export and every repr(C) record.

export interface FontdoneWasmExports extends WebAssembly.Exports {
  readonly memory: WebAssembly.Memory;
  fontdone_wasm_malloc(size: number): number;
  fontdone_wasm_free(pointer: number, size: number): void;
  fontdone_wasm_open_face_handle(
    fileBase: number,
    fileSize: number,
    faceIndex: bigint,
    sizePt: number,
    outError: number,
  ): number;
  fontdone_wasm_done_face(handle: number): number;
  fontdone_wasm_set_pixel_sizes(
    handle: number,
    pixelWidth: number,
    pixelHeight: number,
  ): number;
  fontdone_wasm_get_char_index(handle: number, charCode: bigint): number;
  fontdone_wasm_load_glyph(
    handle: number,
    glyphIndex: number,
    loadFlags: number,
  ): number;
  fontdone_wasm_render_glyph(handle: number, renderMode: number): number;
  fontdone_wasm_bitmap_buffer(handle: number): number;
  fontdone_wasm_bitmap_len(handle: number): number;
  fontdone_wasm_bitmap_width(handle: number): number;
  fontdone_wasm_bitmap_rows(handle: number): number;
  fontdone_wasm_bitmap_pitch(handle: number): number;
}
