#!/usr/bin/env python3
"""Build the traced C consumer linked only to Fontdone's C ABI artifact.

The normal unified oracle and this executable compile the same C source against
the pinned FreeType headers.  The normal executable links to pinned FreeType;
this executable links to ``fontdone-c-abi`` and redirects every public
FreeType call through a generated tracing wrapper.  The runtime parity harness
uses those trace events to prove that a subject function was actually called.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def parameter_names(params: str) -> list[str]:
    if params.strip() in {"", "void"}:
        return []
    names = []
    for parameter in params.split(","):
        match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^]]*\])?\s*$", parameter)
        if not match:
            raise ValueError(f"cannot extract parameter name from {parameter!r}")
        names.append(match.group(1))
    return names


def generate_redirect_header(functions: list[dict]) -> str:
    lines = [
        "/* Generated by scripts/build_external_c_oracle.py; do not edit. */",
        "#ifndef FONTDONE_EXTERNAL_TRACE_REDIRECTS_H_",
        "#define FONTDONE_EXTERNAL_TRACE_REDIRECTS_H_",
    ]
    for row in functions:
        symbol = row["symbol"]
        lines.append(f"#define {symbol} fontdone_trace_{symbol}")
    lines.extend(["#endif", ""])
    return "\n".join(lines)


def generate_reapply_header(functions: list[dict]) -> str:
    lines = [
        "/* Generated by scripts/build_external_c_oracle.py; do not edit. */",
    ]
    for row in functions:
        symbol = row["symbol"]
        lines.extend(
            [
                f"#undef {symbol}",
                f"#define {symbol} fontdone_trace_{symbol}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def generate_trace_source(functions: list[dict]) -> str:
    lines = [
        "/* Generated by scripts/build_external_c_oracle.py; do not edit. */",
        '#include "fontdone_ffi.h"',
        "",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "",
        "static FILE* fontdone_trace_file;",
        "static unsigned long fontdone_trace_case;",
        "",
        "void fontdone_external_trace_case_begin(unsigned long case_index) {",
        "    fontdone_trace_case = case_index;",
        "    if (!fontdone_trace_file) {",
        '        const char* path = getenv("FONTDONE_EXTERNAL_TRACE_FILE");',
        '        if (path && path[0] != \'\\0\') fontdone_trace_file = fopen(path, "w");',
        "    }",
        "}",
        "",
        "static void fontdone_external_trace_call(const char* symbol) {",
        "    if (!fontdone_trace_file) return;",
        '    fprintf(fontdone_trace_file, "%lu\\t%s\\n", fontdone_trace_case, symbol);',
        "    fflush(fontdone_trace_file);",
        "}",
        "",
    ]
    for row in functions:
        symbol = row["symbol"]
        return_type = row["c_return"]
        params = row["c_params"]
        arguments = ", ".join(parameter_names(params))
        lines.extend(
            [
                f"{return_type} fontdone_trace_{symbol}({params}) {{",
                f'    fontdone_external_trace_call("{symbol}");',
            ]
        )
        if return_type == "void":
            lines.append(f"    {symbol}({arguments});")
        else:
            lines.append(f"    return {symbol}({arguments});")
        lines.extend(["}", ""])
    return "\n".join(lines)


def shared_library(cargo_target_dir: pathlib.Path) -> pathlib.Path:
    release = cargo_target_dir / "release"
    candidates = [
        release / "libfontdone_c_abi.dylib",
        release / "libfontdone_c_abi.so",
        release / "fontdone_c_abi.dll",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        "missing fontdone-c-abi shared library; run "
        "`cargo build --release -p fontdone-c-abi`"
    )


def write_if_changed(path: pathlib.Path, contents: str) -> None:
    if path.exists() and path.read_text() == contents:
        return
    path.write_text(contents)


def inspect_dynamic_dependencies(executable: pathlib.Path) -> dict:
    if shutil.which("otool"):
        command = ["otool", "-L", str(executable)]
    elif shutil.which("readelf"):
        command = ["readelf", "-d", str(executable)]
    else:
        raise OSError("neither otool nor readelf is available for dependency inspection")
    output = subprocess.run(
        command, check=True, text=True, stdout=subprocess.PIPE
    ).stdout
    lowered = output.lower()
    fontdone_present = "fontdone_c_abi" in lowered
    freetype_present = re.search(r"(?:^|[/\\s])libfreetype(?:[.\\s]|$)", lowered, re.M)
    if not fontdone_present:
        raise ValueError("external C executable does not depend on fontdone_c_abi")
    if freetype_present:
        raise ValueError("external C executable unexpectedly depends on libfreetype")
    return {
        "command": command,
        "output": output,
        "fontdone_c_abi_present": fontdone_present,
        "libfreetype_present": bool(freetype_present),
    }


def run_json(command: list[str], environment=None) -> dict:
    completed = subprocess.run(
        command,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=environment,
    )
    value = json.loads(completed.stdout)
    if not isinstance(value, dict):
        raise ValueError(f"command did not emit a JSON object: {command}")
    return value


def freetype_library(build_dir: pathlib.Path) -> pathlib.Path:
    candidates = [
        build_dir / "libfreetype.so",
        build_dir / "libfreetype.dylib",
    ]
    candidates.extend(sorted(build_dir.glob("libfreetype*.so*")))
    candidates.extend(sorted(build_dir.glob("libfreetype*.dylib")))
    candidates.extend(sorted(build_dir.glob("libfreetype*.a")))
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"no pinned FreeType library in {build_dir}")


def verify_lzw_disabled_contract(
    root: pathlib.Path,
    external: pathlib.Path,
    fontdone_library: pathlib.Path,
    cargo_target_dir: pathlib.Path,
    build_manifest: pathlib.Path,
) -> None:
    case_id = "ftlzw.FT_Stream_OpenLZW.unsupported_build_error"
    fixture = root / "tests" / "fixtures" / "compressed" / "lzw" / "small-valid-pcf.Z"
    pinned_oracle = (
        root / "target" / "unified-fixtures" / "gen_unified_oracle_lzw_disabled"
    )
    probe = (
        cargo_target_dir
        / "release"
        / "examples"
        / f"optional_feature_probe{'.exe' if os.name == 'nt' else ''}"
    )
    pinned_build = root / "freetype" / "build-lzw-disabled"
    pinned_library = freetype_library(pinned_build)
    option_header = (
        root
        / "target"
        / "oracle-config"
        / "lzw-disabled"
        / "fontdone_ftoption_lzw_disabled.h"
    )
    if "#undef FT_CONFIG_OPTION_USE_LZW" not in option_header.read_text():
        raise ValueError("LZW-disabled pinned option header still enables LZW")

    pinned_environment = os.environ.copy()
    pinned_environment["LD_LIBRARY_PATH"] = str(pinned_build)
    pinned_environment["DYLD_LIBRARY_PATH"] = str(pinned_build)
    fontdone_environment = os.environ.copy()
    fontdone_environment["LD_LIBRARY_PATH"] = str(fontdone_library.parent)
    fontdone_environment["DYLD_LIBRARY_PATH"] = str(fontdone_library.parent)
    commands = {
        "pinned_c": [
            str(pinned_oracle),
            "--lzw-stream-case",
            case_id,
            str(fixture),
        ],
        "rust_ffi": [str(probe), "lzw", "rust"],
        "external_c": [
            str(external),
            "--lzw-stream-case",
            case_id,
            str(fixture),
        ],
        "wasm_host": [str(probe), "lzw", "wasm"],
    }
    outputs = {
        "pinned_c": run_json(commands["pinned_c"], pinned_environment),
        "rust_ffi": run_json(commands["rust_ffi"]),
        "external_c": run_json(commands["external_c"], fontdone_environment),
        "wasm_host": run_json(commands["wasm_host"]),
    }
    expected = outputs["pinned_c"]
    mismatches = [
        name for name, output in outputs.items() if output != expected
    ]
    status = expected.get("status", {})
    rows = expected.get("output", {}).get("rows", [])
    if (
        status.get("kind") != "error"
        or status.get("error_code") != 7
        or len(rows) != 2
        or any(row.get("status") != 7 for row in rows)
        or rows[1].get("target_stream_before")
        != rows[1].get("target_stream_after")
    ):
        raise ValueError(f"invalid pinned LZW-disabled contract output: {expected}")
    if mismatches:
        raise ValueError(
            "LZW-disabled contract mismatch: " + ", ".join(mismatches)
        )

    normalized = json.dumps(expected, sort_keys=True, separators=(",", ":"))
    ledger = {
        "schema_version": 1,
        "pinned_freetype_version": "2.14.3",
        "case_id": case_id,
        "measurement": (
            "The same null and valid argument matrix executes through an "
            "isolated pinned FreeType build, no-default-feature Rust FFI, "
            "separately linked C artifact, and no-default-feature WASM host."
        ),
        "status": "exact",
        "lanes": 4,
        "normalized_output_sha256": hashlib.sha256(
            normalized.encode()
        ).hexdigest(),
        "identity": {
            "option_header": str(option_header.relative_to(root)),
            "option_header_sha256": sha256(option_header),
            "pinned_library": str(pinned_library.relative_to(root)),
            "pinned_library_sha256": sha256(pinned_library),
            "pinned_oracle": str(pinned_oracle.relative_to(root)),
            "pinned_oracle_sha256": sha256(pinned_oracle),
            "fontdone_library": str(fontdone_library.relative_to(root)),
            "fontdone_library_sha256": sha256(fontdone_library),
            "external_c": str(external.relative_to(root)),
            "external_c_sha256": sha256(external),
            "rust_wasm_probe": str(probe.relative_to(root)),
            "rust_wasm_probe_sha256": sha256(probe),
            "external_build_manifest": str(build_manifest.relative_to(root)),
            "external_build_manifest_sha256": sha256(build_manifest),
            "fixture": str(fixture.relative_to(root)),
            "fixture_sha256": sha256(fixture),
        },
        "commands": commands,
        "outputs": outputs,
    }
    ledger_path = (
        root / "target" / "api-abi-audit" / "lzw_disabled_contract_ledger.json"
    )
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2) + "\n")
    print(
        "LZW-disabled contract: "
        f"4/4 exact sha256={ledger['normalized_output_sha256']}"
    )


def verify_bzip2_disabled_contract(
    root: pathlib.Path,
    external: pathlib.Path,
    fontdone_library: pathlib.Path,
    cargo_target_dir: pathlib.Path,
    build_manifest: pathlib.Path,
) -> None:
    case_ids = [
        "ftbzip2.FT_Stream_OpenBzip2.out_of_scope_uncompiled_bzip2_policy",
        "ftbzip2.FT_Stream_OpenBzip2.disabled_build_precedes_null_validation",
        "ftbzip2.FT_Stream_OpenBzip2.disabled_build_precedes_header_validation",
    ]
    pinned_oracle = root / "target" / "unified-fixtures" / "gen_unified_oracle"
    probe = (
        cargo_target_dir
        / "release"
        / "examples"
        / f"optional_feature_probe{'.exe' if os.name == 'nt' else ''}"
    )
    pinned_build = root / "freetype" / "build"
    pinned_library = freetype_library(pinned_build)
    cmake_cache = pinned_build / "CMakeCache.txt"
    if "FT_DISABLE_BZIP2:BOOL=ON" not in cmake_cache.read_text():
        raise ValueError("default pinned build does not prove Bzip2 is disabled")

    pinned_environment = os.environ.copy()
    pinned_environment["LD_LIBRARY_PATH"] = str(pinned_build)
    pinned_environment["DYLD_LIBRARY_PATH"] = str(pinned_build)
    fontdone_environment = os.environ.copy()
    fontdone_environment["LD_LIBRARY_PATH"] = str(fontdone_library.parent)
    fontdone_environment["DYLD_LIBRARY_PATH"] = str(fontdone_library.parent)
    commands = {
        "pinned_c": [str(pinned_oracle), "--bzip2-stream-disabled-policy"],
        "rust_ffi": [str(probe), "bzip2", "rust"],
        "external_c": [str(external), "--bzip2-stream-disabled-policy"],
        "wasm_host": [str(probe), "bzip2", "wasm"],
    }
    outputs = {
        "pinned_c": run_json(commands["pinned_c"], pinned_environment),
        "rust_ffi": run_json(commands["rust_ffi"]),
        "external_c": run_json(commands["external_c"], fontdone_environment),
        "wasm_host": run_json(commands["wasm_host"]),
    }
    expected = outputs["pinned_c"]
    mismatches = [
        name for name, output in outputs.items() if output != expected
    ]
    status = expected.get("status", {})
    output = expected.get("output", {})
    stream = output.get("stream", {})
    if (
        status.get("kind") != "error"
        or status.get("error_code") != 7
        or output.get("build_features") != {"bzip2": False}
        or output.get("error") != 7
        or stream
        != {
            "base_class": "null",
            "read_class": "null",
            "close_class": "null",
        }
    ):
        raise ValueError(f"invalid pinned Bzip2-disabled contract output: {expected}")
    if mismatches:
        raise ValueError(
            "Bzip2-disabled contract mismatch: " + ", ".join(mismatches)
        )

    normalized = json.dumps(expected, sort_keys=True, separators=(",", ":"))
    ledger = {
        "schema_version": 1,
        "pinned_freetype_version": "2.14.3",
        "case_ids": case_ids,
        "measurement": (
            "The same disabled-feature entry executes through the default "
            "Bzip2-disabled pinned FreeType build, no-default-feature Rust "
            "FFI, separately linked C artifact, and no-default-feature WASM host."
        ),
        "status": "exact",
        "lanes": 4,
        "routes": len(case_ids),
        "normalized_output_sha256": hashlib.sha256(
            normalized.encode()
        ).hexdigest(),
        "identity": {
            "cmake_cache": str(cmake_cache.relative_to(root)),
            "cmake_cache_sha256": sha256(cmake_cache),
            "pinned_library": str(pinned_library.relative_to(root)),
            "pinned_library_sha256": sha256(pinned_library),
            "pinned_oracle": str(pinned_oracle.relative_to(root)),
            "pinned_oracle_sha256": sha256(pinned_oracle),
            "fontdone_library": str(fontdone_library.relative_to(root)),
            "fontdone_library_sha256": sha256(fontdone_library),
            "external_c": str(external.relative_to(root)),
            "external_c_sha256": sha256(external),
            "rust_wasm_probe": str(probe.relative_to(root)),
            "rust_wasm_probe_sha256": sha256(probe),
            "external_build_manifest": str(build_manifest.relative_to(root)),
            "external_build_manifest_sha256": sha256(build_manifest),
        },
        "commands": commands,
        "outputs": outputs,
    }
    ledger_path = (
        root / "target" / "api-abi-audit" / "bzip2_disabled_contract_ledger.json"
    )
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2) + "\n")
    print(
        "Bzip2-disabled contract: "
        f"4/4 lanes, {len(case_ids)}/{len(case_ids)} routes exact "
        f"sha256={ledger['normalized_output_sha256']}"
    )


def verify_lcd_filtering_disabled_contract(
    root: pathlib.Path,
    external: pathlib.Path,
    fontdone_library: pathlib.Path,
    cargo_target_dir: pathlib.Path,
    build_manifest: pathlib.Path,
) -> None:
    case_ids = [
        (
            "ftlcdfil.FT_Library_SetLcdFilter."
            "unimplemented_without_subpixel_filtering"
        ),
        (
            "ftlcdfil.FT_Library_SetLcdFilterWeights."
            "unimplemented_without_subpixel_filtering"
        ),
    ]
    scenarios = {
        "filter_live_library": ["--set-lcd-filter", "1", "1"],
        "filter_null_library": ["--set-lcd-filter", "0", "1"],
        "weights_live_library": [
            "--set-lcd-filter-weights",
            "1",
            "16,32,64,32,16",
        ],
        "weights_null_library": [
            "--set-lcd-filter-weights",
            "0",
            "16,32,64,32,16",
        ],
        "weights_null_pointer": ["--set-lcd-filter-weights", "1", "-"],
    }
    pinned_oracle = root / "target" / "unified-fixtures" / "gen_unified_oracle"
    probe = (
        cargo_target_dir
        / "release"
        / "examples"
        / f"optional_feature_probe{'.exe' if os.name == 'nt' else ''}"
    )
    pinned_build = root / "freetype" / "build"
    pinned_library = freetype_library(pinned_build)
    pinned_environment = os.environ.copy()
    pinned_environment["LD_LIBRARY_PATH"] = str(pinned_build)
    pinned_environment["DYLD_LIBRARY_PATH"] = str(pinned_build)
    fontdone_environment = os.environ.copy()
    fontdone_environment["LD_LIBRARY_PATH"] = str(fontdone_library.parent)
    fontdone_environment["DYLD_LIBRARY_PATH"] = str(fontdone_library.parent)

    all_commands = {}
    all_outputs = {}
    for scenario, route in scenarios.items():
        commands = {
            "pinned_c": [str(pinned_oracle), *route],
            "rust_ffi": [
                str(probe),
                "lcd-filtering-disabled",
                "rust",
                *route,
            ],
            "external_c": [str(external), *route],
            "wasm_host": [
                str(probe),
                "lcd-filtering-disabled",
                "wasm",
                *route,
            ],
        }
        outputs = {
            "pinned_c": run_json(commands["pinned_c"], pinned_environment),
            "rust_ffi": run_json(commands["rust_ffi"]),
            "external_c": run_json(commands["external_c"], fontdone_environment),
            "wasm_host": run_json(commands["wasm_host"]),
        }
        expected = outputs["pinned_c"]
        mismatches = [
            name for name, output in outputs.items() if output != expected
        ]
        if expected.get("status") != {"kind": "error", "error_code": 7}:
            raise ValueError(
                f"invalid pinned LCD-filtering-disabled output for {scenario}: "
                f"{expected}"
            )
        if mismatches:
            raise ValueError(
                f"{scenario} LCD-filtering-disabled mismatch: "
                + ", ".join(mismatches)
            )
        all_commands[scenario] = commands
        all_outputs[scenario] = outputs

    normalized = json.dumps(
        {
            scenario: outputs["pinned_c"]
            for scenario, outputs in all_outputs.items()
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    ledger = {
        "schema_version": 1,
        "pinned_freetype_version": "2.14.3",
        "case_ids": case_ids,
        "scenarios": list(scenarios),
        "measurement": (
            "Live and null libraries plus valid and null weight pointers all "
            "return Unimplemented_Feature before validation in the default "
            "subpixel-filtering-disabled pinned C, Rust FFI, separately "
            "linked C artifact, and WASM host builds."
        ),
        "status": "exact",
        "lanes": 4,
        "routes": len(case_ids),
        "scenario_count": len(scenarios),
        "normalized_output_sha256": hashlib.sha256(
            normalized.encode()
        ).hexdigest(),
        "identity": {
            "pinned_library": str(pinned_library.relative_to(root)),
            "pinned_library_sha256": sha256(pinned_library),
            "pinned_oracle": str(pinned_oracle.relative_to(root)),
            "pinned_oracle_sha256": sha256(pinned_oracle),
            "fontdone_library": str(fontdone_library.relative_to(root)),
            "fontdone_library_sha256": sha256(fontdone_library),
            "external_c": str(external.relative_to(root)),
            "external_c_sha256": sha256(external),
            "rust_wasm_probe": str(probe.relative_to(root)),
            "rust_wasm_probe_sha256": sha256(probe),
            "external_build_manifest": str(build_manifest.relative_to(root)),
            "external_build_manifest_sha256": sha256(build_manifest),
        },
        "commands": all_commands,
        "outputs": all_outputs,
    }
    ledger_path = (
        root
        / "target"
        / "api-abi-audit"
        / "lcd_filtering_disabled_contract_ledger.json"
    )
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2) + "\n")
    print(
        "LCD-filtering-disabled contract: "
        f"4/4 lanes, {len(case_ids)}/{len(case_ids)} routes, "
        f"{len(scenarios)}/{len(scenarios)} scenarios exact "
        f"sha256={ledger['normalized_output_sha256']}"
    )


def verify_color_layers_disabled_contract(
    root: pathlib.Path,
    external: pathlib.Path,
    fontdone_library: pathlib.Path,
    cargo_target_dir: pathlib.Path,
    build_manifest: pathlib.Path,
) -> None:
    case_ids = [
        "ftcolor.FT_Palette_Data_Get.error_color_layers_disabled",
        "ftcolor.FT_Palette_Select.error_color_layers_disabled",
        "ftcolor.FT_Palette_Set_Foreground_Color.error_color_layers_disabled",
    ]
    fixture = (
        root
        / "tests"
        / "fixtures"
        / "input"
        / "fonts"
        / "color"
        / "cpal-palettes-names-flags.ttf"
    )
    pinned_oracle = (
        root
        / "target"
        / "unified-fixtures"
        / "gen_unified_oracle_color_layers_disabled"
    )
    probe = (
        cargo_target_dir
        / "release"
        / "examples"
        / f"optional_feature_probe{'.exe' if os.name == 'nt' else ''}"
    )
    pinned_build = root / "freetype" / "build-color-layers-disabled"
    pinned_library = freetype_library(pinned_build)
    option_header = (
        root
        / "target"
        / "oracle-config"
        / "color-layers-disabled"
        / "fontdone_ftoption_color_layers_disabled.h"
    )
    if "#undef TT_CONFIG_OPTION_COLOR_LAYERS" not in option_header.read_text():
        raise ValueError(
            "color-layers-disabled pinned option header still enables color layers"
        )

    pinned_environment = os.environ.copy()
    pinned_environment["LD_LIBRARY_PATH"] = str(pinned_build)
    pinned_environment["DYLD_LIBRARY_PATH"] = str(pinned_build)
    fontdone_environment = os.environ.copy()
    fontdone_environment["LD_LIBRARY_PATH"] = str(fontdone_library.parent)
    fontdone_environment["DYLD_LIBRARY_PATH"] = str(fontdone_library.parent)
    route = ["--palette-disabled-contract", str(fixture), "0"]
    commands = {
        "pinned_c": [str(pinned_oracle), *route],
        "rust_ffi": [str(probe), "color-layers", "rust", str(fixture), "0"],
        "external_c": [str(external), *route],
        "wasm_host": [str(probe), "color-layers", "wasm", str(fixture), "0"],
    }
    outputs = {
        "pinned_c": run_json(commands["pinned_c"], pinned_environment),
        "rust_ffi": run_json(commands["rust_ffi"]),
        "external_c": run_json(commands["external_c"], fontdone_environment),
        "wasm_host": run_json(commands["wasm_host"]),
    }
    expected = outputs["pinned_c"]
    mismatches = [
        name for name, output in outputs.items() if output != expected
    ]
    status = expected.get("status", {})
    output = expected.get("output", {})
    data_get = output.get("data_get", {})
    select = output.get("select", {})
    foreground = output.get("set_foreground_color", {})
    if (
        status != {"kind": "error", "error_code": 7}
        or output.get("build_features") != {"color_layers": False}
        or data_get.get("error") != 7
        or data_get.get("palette_data_snapshot")
        != {
            "num_palettes": 999,
            "num_palette_entries": 999,
            "pointer_nullness": {
                "palette_name_ids": False,
                "palette_flags": False,
                "palette_entry_name_ids": False,
            },
        }
        or select != {"error": 7, "apalette_snapshot": "non_null"}
        or foreground != {"error": 7}
    ):
        raise ValueError(
            f"invalid pinned color-layers-disabled contract output: {expected}"
        )
    if mismatches:
        raise ValueError(
            "color-layers-disabled contract mismatch: " + ", ".join(mismatches)
        )

    normalized = json.dumps(expected, sort_keys=True, separators=(",", ":"))
    ledger = {
        "schema_version": 1,
        "pinned_freetype_version": "2.14.3",
        "case_ids": case_ids,
        "measurement": (
            "The same CPAL-backed face executes all three disabled palette "
            "entries through an isolated pinned FreeType build, "
            "no-default-feature Rust FFI, separately linked C artifact, and "
            "no-default-feature WASM host. Sentinel outputs prove the stubs "
            "preserve caller storage."
        ),
        "status": "exact",
        "lanes": 4,
        "routes": len(case_ids),
        "normalized_output_sha256": hashlib.sha256(
            normalized.encode()
        ).hexdigest(),
        "identity": {
            "option_header": str(option_header.relative_to(root)),
            "option_header_sha256": sha256(option_header),
            "pinned_library": str(pinned_library.relative_to(root)),
            "pinned_library_sha256": sha256(pinned_library),
            "pinned_oracle": str(pinned_oracle.relative_to(root)),
            "pinned_oracle_sha256": sha256(pinned_oracle),
            "fontdone_library": str(fontdone_library.relative_to(root)),
            "fontdone_library_sha256": sha256(fontdone_library),
            "external_c": str(external.relative_to(root)),
            "external_c_sha256": sha256(external),
            "rust_wasm_probe": str(probe.relative_to(root)),
            "rust_wasm_probe_sha256": sha256(probe),
            "external_build_manifest": str(build_manifest.relative_to(root)),
            "external_build_manifest_sha256": sha256(build_manifest),
            "fixture": str(fixture.relative_to(root)),
            "fixture_sha256": sha256(fixture),
        },
        "commands": commands,
        "outputs": outputs,
    }
    ledger_path = (
        root
        / "target"
        / "api-abi-audit"
        / "color_layers_disabled_contract_ledger.json"
    )
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2) + "\n")
    print(
        "Color-layers-disabled contract: "
        f"4/4 lanes, {len(case_ids)}/{len(case_ids)} routes exact "
        f"sha256={ledger['normalized_output_sha256']}"
    )


def verify_subpixel_rendering_enabled_contract(
    root: pathlib.Path,
    external: pathlib.Path,
    fontdone_library: pathlib.Path,
    cargo_target_dir: pathlib.Path,
    build_manifest: pathlib.Path,
) -> None:
    routes = {
        "ftlcdfil.FT_Library_SetLcdFilter.success_sets_none_default_light": [
            "--set-lcd-filter",
            "1",
            "0,1,2",
        ],
        "ftlcdfil.FT_Library_SetLcdFilter.error_null_library": [
            "--set-lcd-filter",
            "0",
            "1",
        ],
        "ftlcdfil.FT_Library_SetLcdFilter.error_invalid_filter": [
            "--set-lcd-filter",
            "1",
            "3,16,4,99",
        ],
        "ftlcdfil.FT_Library_SetLcdFilterWeights.success_copies_five_weights": [
            "--set-lcd-filter-weights",
            "1",
            "16,32,64,32,16,255",
        ],
        "ftlcdfil.FT_Library_SetLcdFilterWeights.error_null_library": [
            "--set-lcd-filter-weights",
            "0",
            "16,32,64,32,16",
        ],
        "ftlcdfil.FT_Library_SetLcdFilterWeights.error_null_weights": [
            "--set-lcd-filter-weights",
            "1",
            "-",
        ],
        (
            "ftlcdfil.FT_Library_SetLcdGeometry."
            "unimplemented_with_subpixel_filtering"
        ): [
            "--set-lcd-geometry",
            "1",
            "-21,0;0,0;21,0",
        ],
    }
    pinned_oracle = (
        root
        / "target"
        / "unified-fixtures"
        / "gen_unified_oracle_subpixel_rendering_enabled"
    )
    probe = (
        cargo_target_dir
        / "release"
        / "examples"
        / f"optional_feature_probe{'.exe' if os.name == 'nt' else ''}"
    )
    pinned_build = root / "freetype" / "build-subpixel-rendering-enabled"
    pinned_library = freetype_library(pinned_build)
    option_header = (
        root
        / "target"
        / "oracle-config"
        / "subpixel-rendering-enabled"
        / "fontdone_ftoption_subpixel_rendering_enabled.h"
    )
    if "#define FT_CONFIG_OPTION_SUBPIXEL_RENDERING" not in option_header.read_text():
        raise ValueError(
            "subpixel-rendering-enabled pinned option header does not enable the option"
        )

    pinned_environment = os.environ.copy()
    pinned_environment["LD_LIBRARY_PATH"] = str(pinned_build)
    pinned_environment["DYLD_LIBRARY_PATH"] = str(pinned_build)
    fontdone_environment = os.environ.copy()
    fontdone_environment["LD_LIBRARY_PATH"] = str(fontdone_library.parent)
    fontdone_environment["DYLD_LIBRARY_PATH"] = str(fontdone_library.parent)
    all_commands = {}
    all_outputs = {}
    for case_id, route in routes.items():
        commands = {
            "pinned_c": [str(pinned_oracle), *route],
            "rust_ffi": [
                str(probe),
                "subpixel-rendering",
                "rust",
                *route,
            ],
            "external_c": [str(external), *route],
            "wasm_host": [
                str(probe),
                "subpixel-rendering",
                "wasm",
                *route,
            ],
        }
        outputs = {
            "pinned_c": run_json(commands["pinned_c"], pinned_environment),
            "rust_ffi": run_json(commands["rust_ffi"]),
            "external_c": run_json(commands["external_c"], fontdone_environment),
            "wasm_host": run_json(commands["wasm_host"]),
        }
        expected = outputs["pinned_c"]
        mismatches = [
            name for name, output in outputs.items() if output != expected
        ]
        if mismatches:
            raise ValueError(
                f"{case_id} subpixel contract mismatch: " + ", ".join(mismatches)
            )
        all_commands[case_id] = commands
        all_outputs[case_id] = outputs

    filter_success = all_outputs[
        "ftlcdfil.FT_Library_SetLcdFilter.success_sets_none_default_light"
    ]["pinned_c"]
    success_rows = filter_success.get("output", {}).get("outputs", [])
    expected_weights = {
        0: [0, 0, 0, 0, 0],
        1: [8, 77, 86, 77, 8],
        2: [0, 85, 86, 85, 0],
    }
    if (
        filter_success.get("status") != {"kind": "ok", "error_code": 0}
        or len(success_rows) != 3
        or any(
            row.get("error") != 0
            or row.get("library_weights") != expected_weights.get(row.get("filter"))
            for row in success_rows
        )
    ):
        raise ValueError(f"invalid enabled LCD filter state output: {filter_success}")

    invalid_rows = all_outputs[
        "ftlcdfil.FT_Library_SetLcdFilter.error_invalid_filter"
    ]["pinned_c"].get("output", {}).get("outputs", [])
    if (
        len(invalid_rows) != 4
        or any(row.get("error") == 0 for row in invalid_rows)
        or any(
            row.get("library_weights") != [8, 77, 86, 77, 8]
            for row in invalid_rows
        )
    ):
        raise ValueError(f"invalid LCD filter rejection state: {invalid_rows}")

    weights_success = all_outputs[
        "ftlcdfil.FT_Library_SetLcdFilterWeights.success_copies_five_weights"
    ]["pinned_c"]
    if weights_success.get("output") != {
        "error": 0,
        "library_weights": [16, 32, 64, 32, 16],
        "ignored_tail_bytes": [255],
    }:
        raise ValueError(f"invalid five-byte LCD weight copy: {weights_success}")

    geometry = all_outputs[
        (
            "ftlcdfil.FT_Library_SetLcdGeometry."
            "unimplemented_with_subpixel_filtering"
        )
    ]["pinned_c"]
    if (
        geometry.get("status") != {"kind": "error", "error_code": 7}
        or geometry.get("output")
        != {"error": 7, "feature_branch": "subpixel_rendering"}
    ):
        raise ValueError(f"invalid enabled-branch LCD geometry output: {geometry}")

    normalized = json.dumps(
        {
            case_id: outputs["pinned_c"]
            for case_id, outputs in all_outputs.items()
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    ledger = {
        "schema_version": 1,
        "pinned_freetype_version": "2.14.3",
        "case_ids": list(routes),
        "measurement": (
            "Every enabled ClearType-style LCD setter route executes through "
            "an isolated pinned FreeType build, feature-matched Rust FFI, a "
            "separately linked C artifact, and the feature-matched WASM host. "
            "Stored weights prove presets, error-state preservation, and the "
            "five-byte copy boundary."
        ),
        "status": "exact",
        "lanes": 4,
        "routes": len(routes),
        "normalized_output_sha256": hashlib.sha256(
            normalized.encode()
        ).hexdigest(),
        "identity": {
            "option_header": str(option_header.relative_to(root)),
            "option_header_sha256": sha256(option_header),
            "pinned_library": str(pinned_library.relative_to(root)),
            "pinned_library_sha256": sha256(pinned_library),
            "pinned_oracle": str(pinned_oracle.relative_to(root)),
            "pinned_oracle_sha256": sha256(pinned_oracle),
            "fontdone_library": str(fontdone_library.relative_to(root)),
            "fontdone_library_sha256": sha256(fontdone_library),
            "external_c": str(external.relative_to(root)),
            "external_c_sha256": sha256(external),
            "rust_wasm_probe": str(probe.relative_to(root)),
            "rust_wasm_probe_sha256": sha256(probe),
            "external_build_manifest": str(build_manifest.relative_to(root)),
            "external_build_manifest_sha256": sha256(build_manifest),
        },
        "commands": all_commands,
        "outputs": all_outputs,
    }
    ledger_path = (
        root
        / "target"
        / "api-abi-audit"
        / "subpixel_rendering_enabled_contract_ledger.json"
    )
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2) + "\n")
    print(
        "Subpixel-rendering-enabled LCD contract: "
        f"4/4 lanes, {len(routes)}/{len(routes)} routes exact "
        f"sha256={ledger['normalized_output_sha256']}"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out", default="target/unified-fixtures/gen_fontdone_external"
    )
    parser.add_argument("--cargo-target-dir", default="target")
    parser.add_argument("--constants-dir", default="target/unified-fixtures")
    parser.add_argument(
        "--verify-optional-features-disabled",
        action="store_true",
    )
    parser.add_argument(
        "--verify-subpixel-rendering-enabled",
        action="store_true",
    )
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    output = root / args.out
    cargo_target_dir = root / args.cargo_target_dir
    build_dir = output.parent
    build_dir.mkdir(parents=True, exist_ok=True)
    audit_path = root / "target" / "api-abi-audit" / "api_abi_audit.json"
    if not audit_path.exists():
        raise SystemExit("missing API audit; run `make api-abi-audit` first")
    functions = json.loads(audit_path.read_text())["functions"]
    if len(functions) != 218:
        raise SystemExit(f"expected 218 pinned functions, found {len(functions)}")

    redirects = build_dir / "fontdone_external_trace_redirects.h"
    reapply = build_dir / "fontdone_external_trace_reapply.h"
    trace_source = build_dir / "fontdone_external_trace.c"
    oracle_object = build_dir / "gen_fontdone_external_oracle.o"
    trace_object = build_dir / "gen_fontdone_external_trace.o"
    build_manifest = build_dir / "gen_fontdone_external.build.json"
    write_if_changed(redirects, generate_redirect_header(functions))
    write_if_changed(reapply, generate_reapply_header(functions))
    write_if_changed(trace_source, generate_trace_source(functions))

    cc = os.environ.get("CC", "cc")
    source = root / "scripts" / "gen_unified_oracle.c"
    constants_dir = root / args.constants_dir
    pinned_include = root / "freetype" / "include"
    local_include = root / "fontdone-c-abi" / "include"
    library = shared_library(cargo_target_dir)

    compile_oracle = [
        cc,
        "-std=c11",
        "-DFONTDONE_EXTERNAL_TRACE=1",
        "-include",
        str(redirects),
        "-I",
        str(pinned_include),
        # The generated trace reapply header lives beside each external
        # optional-feature executable, not in the shared constants directory.
        "-I",
        str(build_dir),
        "-I",
        str(constants_dir),
        "-c",
        str(source),
        "-o",
        str(oracle_object),
    ]
    option_header = None
    if args.verify_subpixel_rendering_enabled:
        config_dir = (
            root / "target" / "oracle-config" / "subpixel-rendering-enabled"
        )
        option_header = (
            config_dir / "fontdone_ftconfig_subpixel_rendering_enabled.h"
        )
        compile_oracle[2:2] = [
            "-include",
            str(option_header),
            "-I",
            str(config_dir),
        ]
    compile_trace = [
        cc,
        "-std=c11",
        "-I",
        str(local_include),
        "-c",
        str(trace_source),
        "-o",
        str(trace_object),
    ]
    release = library.parent
    link = [
        cc,
        str(oracle_object),
        str(trace_object),
        "-L",
        str(release),
        f"-Wl,-rpath,{release}",
        "-lfontdone_c_abi",
        "-lm",
        "-o",
        str(output),
    ]
    for command in (compile_oracle, compile_trace, link):
        subprocess.run(command, check=True, cwd=root)
    dependency_inspection = inspect_dynamic_dependencies(output)

    manifest = {
        "schema_version": 1,
        "compiler": cc,
        "source": str(source.relative_to(root)),
        "source_sha256": sha256(source),
        "pinned_headers": str(pinned_include.relative_to(root)),
        "fontdone_header": str(
            (local_include / "fontdone_ffi.h").relative_to(root)
        ),
        "linked_fontdone_library": str(library.relative_to(root)),
        "linked_fontdone_library_sha256": sha256(library),
        "executable": str(output.relative_to(root)),
        "executable_sha256": sha256(output),
        "traced_functions": len(functions),
        "dependency_inspection": dependency_inspection,
        "commands": {
            "compile_oracle": compile_oracle,
            "compile_trace": compile_trace,
            "link": link,
        },
    }
    if option_header is not None:
        manifest["option_header"] = str(option_header.relative_to(root))
        manifest["option_header_sha256"] = sha256(option_header)
    build_manifest.write_text(json.dumps(manifest, indent=2) + "\n")
    if args.verify_optional_features_disabled:
        verify_lzw_disabled_contract(
            root,
            output,
            library,
            cargo_target_dir,
            build_manifest,
        )
        verify_bzip2_disabled_contract(
            root,
            output,
            library,
            cargo_target_dir,
            build_manifest,
        )
        verify_lcd_filtering_disabled_contract(
            root,
            output,
            library,
            cargo_target_dir,
            build_manifest,
        )
        verify_color_layers_disabled_contract(
            root,
            output,
            library,
            cargo_target_dir,
            build_manifest,
        )
    if args.verify_subpixel_rendering_enabled:
        verify_subpixel_rendering_enabled_contract(
            root,
            output,
            library,
            cargo_target_dir,
            build_manifest,
        )
    print(output)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error
