#!/usr/bin/env python3
"""Build the unified C FreeType oracle helper used by fixture tests."""

import argparse
import os
import pathlib
import subprocess
import sys


def freetype_library(build_dir: pathlib.Path) -> pathlib.Path:
    candidates = [
        build_dir / "libfreetype.so",
        build_dir / "libfreetype.dylib",
    ]
    candidates.extend(sorted(build_dir.glob("libfreetype*.so*")))
    candidates.extend(sorted(build_dir.glob("libfreetype*.dylib")))
    candidates.extend(sorted(build_dir.glob("libfreetype*.a")))
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(f"no libfreetype artifact found in {build_dir}")


def write_if_changed(path: pathlib.Path, contents: str) -> None:
    if path.exists() and path.read_text() == contents:
        return
    path.write_text(contents)


def configure_lzw_disabled_freetype(root: pathlib.Path) -> pathlib.Path:
    """Build the pinned source with its LZW option genuinely disabled."""

    config_dir = root / "target" / "oracle-config" / "lzw-disabled"
    config_dir.mkdir(parents=True, exist_ok=True)
    source_options = root / "freetype" / "include" / "freetype" / "config" / "ftoption.h"
    transformed_options = config_dir / "fontdone_ftoption_lzw_disabled.h"
    transformer = root / "freetype" / "builds" / "meson" / "process_ftoption_h.py"
    transformed = subprocess.run(
        [
            sys.executable,
            str(transformer),
            str(source_options),
            "--disable=FT_CONFIG_OPTION_USE_LZW",
        ],
        check=True,
        cwd=root,
        capture_output=True,
        text=True,
    )
    write_if_changed(
        transformed_options,
        transformed.stdout.rstrip("\n") + "\n",
    )
    preinclude = config_dir / "fontdone_ftconfig_lzw_disabled.h"
    write_if_changed(
        preinclude,
        "\n".join(
            [
                "/* Generated by scripts/build_unified_oracle.py; do not edit. */",
                "#ifndef FONTDONE_FTCONFIG_LZW_DISABLED_H_",
                "#define FONTDONE_FTCONFIG_LZW_DISABLED_H_",
                "#define FT_CONFIG_OPTIONS_H <fontdone_ftoption_lzw_disabled.h>",
                "#endif",
                "",
            ]
        )
    )
    project_include = config_dir / "lzw-disabled-options.cmake"
    write_if_changed(
        project_include,
        "\n".join(
            [
                "# Generated by scripts/build_unified_oracle.py; do not edit.",
                "add_compile_options(",
                '  "$<$<COMPILE_LANGUAGE:C>:-include>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:{preinclude}>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:-I{config_dir}>"',
                ")",
                "",
            ]
        )
    )

    build_dir = root / "freetype" / "build-lzw-disabled"
    subprocess.run(
        [
            "cmake",
            "-S",
            str(root / "freetype"),
            "-B",
            str(build_dir),
            "-DCMAKE_BUILD_TYPE=Release",
            "-DBUILD_SHARED_LIBS=ON",
            "-DFT_DISABLE_ZLIB=ON",
            "-DFT_DISABLE_PNG=ON",
            "-DFT_DISABLE_BZIP2=ON",
            "-DFT_DISABLE_BROTLI=ON",
            "-DFT_DISABLE_HARFBUZZ=ON",
            f"-DCMAKE_PROJECT_INCLUDE={project_include}",
        ],
        check=True,
        cwd=root,
    )
    subprocess.run(
        ["cmake", "--build", str(build_dir), "--parallel"],
        check=True,
        cwd=root,
    )
    return build_dir


def configure_color_layers_disabled_freetype(root: pathlib.Path) -> pathlib.Path:
    """Build the pinned source with its color-layer option genuinely disabled."""

    config_dir = root / "target" / "oracle-config" / "color-layers-disabled"
    config_dir.mkdir(parents=True, exist_ok=True)
    source_options = root / "freetype" / "include" / "freetype" / "config" / "ftoption.h"
    transformed_options = config_dir / "fontdone_ftoption_color_layers_disabled.h"
    transformer = root / "freetype" / "builds" / "meson" / "process_ftoption_h.py"
    transformed = subprocess.run(
        [
            sys.executable,
            str(transformer),
            str(source_options),
            "--disable=TT_CONFIG_OPTION_COLOR_LAYERS",
        ],
        check=True,
        cwd=root,
        capture_output=True,
        text=True,
    )
    write_if_changed(
        transformed_options,
        transformed.stdout.rstrip("\n") + "\n",
    )
    preinclude = config_dir / "fontdone_ftconfig_color_layers_disabled.h"
    write_if_changed(
        preinclude,
        "\n".join(
            [
                "/* Generated by scripts/build_unified_oracle.py; do not edit. */",
                "#ifndef FONTDONE_FTCONFIG_COLOR_LAYERS_DISABLED_H_",
                "#define FONTDONE_FTCONFIG_COLOR_LAYERS_DISABLED_H_",
                "#define FT_CONFIG_OPTIONS_H <fontdone_ftoption_color_layers_disabled.h>",
                "#endif",
                "",
            ]
        ),
    )
    project_include = config_dir / "color-layers-disabled-options.cmake"
    write_if_changed(
        project_include,
        "\n".join(
            [
                "# Generated by scripts/build_unified_oracle.py; do not edit.",
                "add_compile_options(",
                '  "$<$<COMPILE_LANGUAGE:C>:-include>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:{preinclude}>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:-I{config_dir}>"',
                ")",
                "",
            ]
        ),
    )

    build_dir = root / "freetype" / "build-color-layers-disabled"
    subprocess.run(
        [
            "cmake",
            "-S",
            str(root / "freetype"),
            "-B",
            str(build_dir),
            "-DCMAKE_BUILD_TYPE=Release",
            "-DBUILD_SHARED_LIBS=ON",
            "-DFT_DISABLE_ZLIB=ON",
            "-DFT_DISABLE_PNG=ON",
            "-DFT_DISABLE_BZIP2=ON",
            "-DFT_DISABLE_BROTLI=ON",
            "-DFT_DISABLE_HARFBUZZ=ON",
            f"-DCMAKE_PROJECT_INCLUDE={project_include}",
        ],
        check=True,
        cwd=root,
    )
    subprocess.run(
        ["cmake", "--build", str(build_dir), "--parallel"],
        check=True,
        cwd=root,
    )
    return build_dir


def configure_subpixel_rendering_enabled_freetype(root: pathlib.Path) -> pathlib.Path:
    """Build the pinned source with ClearType-style LCD filtering enabled."""

    config_dir = root / "target" / "oracle-config" / "subpixel-rendering-enabled"
    config_dir.mkdir(parents=True, exist_ok=True)
    source_options = root / "freetype" / "include" / "freetype" / "config" / "ftoption.h"
    transformed_options = config_dir / "fontdone_ftoption_subpixel_rendering_enabled.h"
    transformer = root / "freetype" / "builds" / "meson" / "process_ftoption_h.py"
    transformed = subprocess.run(
        [
            sys.executable,
            str(transformer),
            str(source_options),
            "--enable=FT_CONFIG_OPTION_SUBPIXEL_RENDERING",
        ],
        check=True,
        cwd=root,
        capture_output=True,
        text=True,
    )
    write_if_changed(transformed_options, transformed.stdout.rstrip("\n") + "\n")
    preinclude = config_dir / "fontdone_ftconfig_subpixel_rendering_enabled.h"
    write_if_changed(
        preinclude,
        "\n".join(
            [
                "/* Generated by scripts/build_unified_oracle.py; do not edit. */",
                "#ifndef FONTDONE_FTCONFIG_SUBPIXEL_RENDERING_ENABLED_H_",
                "#define FONTDONE_FTCONFIG_SUBPIXEL_RENDERING_ENABLED_H_",
                (
                    "#define FT_CONFIG_OPTIONS_H "
                    "<fontdone_ftoption_subpixel_rendering_enabled.h>"
                ),
                "#endif",
                "",
            ]
        ),
    )
    project_include = config_dir / "subpixel-rendering-enabled-options.cmake"
    write_if_changed(
        project_include,
        "\n".join(
            [
                "# Generated by scripts/build_unified_oracle.py; do not edit.",
                "add_compile_options(",
                '  "$<$<COMPILE_LANGUAGE:C>:-include>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:{preinclude}>"',
                f'  "$<$<COMPILE_LANGUAGE:C>:-I{config_dir}>"',
                ")",
                "",
            ]
        ),
    )

    build_dir = root / "freetype" / "build-subpixel-rendering-enabled"
    subprocess.run(
        [
            "cmake",
            "-S",
            str(root / "freetype"),
            "-B",
            str(build_dir),
            "-DCMAKE_BUILD_TYPE=Release",
            "-DBUILD_SHARED_LIBS=ON",
            "-DFT_DISABLE_ZLIB=ON",
            "-DFT_DISABLE_PNG=ON",
            "-DFT_DISABLE_BZIP2=ON",
            "-DFT_DISABLE_BROTLI=ON",
            "-DFT_DISABLE_HARFBUZZ=ON",
            f"-DCMAKE_PROJECT_INCLUDE={project_include}",
        ],
        check=True,
        cwd=root,
    )
    subprocess.run(
        ["cmake", "--build", str(build_dir), "--parallel"],
        check=True,
        cwd=root,
    )
    return build_dir


def configure_bzip2_enabled_freetype(root: pathlib.Path) -> pathlib.Path:
    """Build the pinned source with the optional bzip2 adapter enabled."""

    build_dir = root / "freetype" / "build-bzip2-enabled"
    subprocess.run(
        [
            "cmake",
            "-S",
            str(root / "freetype"),
            "-B",
            str(build_dir),
            "-DCMAKE_BUILD_TYPE=Release",
            "-DBUILD_SHARED_LIBS=ON",
            "-DFT_DISABLE_ZLIB=ON",
            "-DFT_DISABLE_PNG=ON",
            "-DFT_DISABLE_BZIP2=OFF",
            "-DFT_DISABLE_BROTLI=ON",
            "-DFT_DISABLE_HARFBUZZ=ON",
        ],
        check=True,
        cwd=root,
    )
    subprocess.run(
        ["cmake", "--build", str(build_dir), "--parallel"],
        check=True,
        cwd=root,
    )
    return build_dir


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--variant",
        choices=(
            "default",
            "bzip2-enabled",
            "color-layers-disabled",
            "lzw-disabled",
            "subpixel-rendering-enabled",
        ),
        default="default",
    )
    parser.add_argument("--out")
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    default_out = {
        "default": "target/unified-fixtures/gen_unified_oracle",
        "bzip2-enabled": "target/unified-fixtures/gen_unified_oracle_bzip2_enabled",
        "color-layers-disabled": (
            "target/unified-fixtures/gen_unified_oracle_color_layers_disabled"
        ),
        "lzw-disabled": "target/unified-fixtures/gen_unified_oracle_lzw_disabled",
        "subpixel-rendering-enabled": (
            "target/unified-fixtures/gen_unified_oracle_subpixel_rendering_enabled"
        ),
    }[args.variant]
    out = root / (args.out or default_out)
    out.parent.mkdir(parents=True, exist_ok=True)
    source = root / "scripts" / "gen_unified_oracle.c"
    constants = root / "target" / "unified-fixtures" / "generated_constants.inc"
    generator = root / "scripts" / "generate_public_constants.py"
    script = pathlib.Path(__file__).resolve()
    freetype_build = {
        "default": lambda: root / "freetype" / "build",
        "bzip2-enabled": lambda: configure_bzip2_enabled_freetype(root),
        "color-layers-disabled": lambda: configure_color_layers_disabled_freetype(root),
        "lzw-disabled": lambda: configure_lzw_disabled_freetype(root),
        "subpixel-rendering-enabled": lambda: (
            configure_subpixel_rendering_enabled_freetype(root)
        ),
    }[args.variant]()
    library = freetype_library(freetype_build)

    subprocess.run(
        [
            os.environ.get("PYTHON", "python3"),
            str(generator),
            "--oracle-inc",
            str(constants.relative_to(root)),
        ],
        check=True,
        cwd=root,
    )

    if out.exists() and out.stat().st_mtime >= max(
        script.stat().st_mtime,
        source.stat().st_mtime,
        generator.stat().st_mtime,
        constants.stat().st_mtime,
        library.stat().st_mtime,
    ):
        print(out)
        return

    cmd = [
        os.environ.get("CC", "cc"),
        "-std=c11",
        "-I",
        str(root / "freetype" / "include"),
        "-I",
        str(constants.parent),
        str(source),
        "-L",
        str(freetype_build),
        f"-Wl,-rpath,{freetype_build}",
        "-lfreetype",
        "-lm",
        "-o",
        str(out),
    ]
    if args.variant == "default":
        cmd.insert(2, "-DFONTDONE_PINNED_ORACLE_VALIDATORS=1")
    elif args.variant == "subpixel-rendering-enabled":
        config_dir = root / "target" / "oracle-config" / args.variant
        cmd[2:2] = [
            "-include",
            str(config_dir / "fontdone_ftconfig_subpixel_rendering_enabled.h"),
            "-I",
            str(config_dir),
        ]
    subprocess.run(cmd, check=True, cwd=root)
    print(out)


if __name__ == "__main__":
    main()
