#!/usr/bin/env python3
"""Generate the public FreeType 2.14.3 function support matrix."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INTERFACE_MAP = ROOT / "tests" / "data" / "interface_map.json"
OUTPUTS = (
    ROOT / "doc" / "FREETYPE_SUPPORT.md",
    ROOT / "fontdone-c-abi" / "API_SUPPORT.md",
)

# These classic Mac helper declarations are recorded by the migration manifest
# for an explicit disposition, but they are not part of the pinned 2.14.3
# public-header inventory produced by scripts/audit_api_abi.py.
LEGACY_MAC_HELPERS = {
    "FT_GetFilePath_From_Mac_ATS_Name",
    "FT_GetFile_From_Mac_ATS_Name",
    "FT_GetFile_From_Mac_Name",
    "FT_New_Face_From_FOND",
    "FT_New_Face_From_FSRef",
    "FT_New_Face_From_FSSpec",
}

STATUS_LABELS = {
    "complete": "Complete",
    "implemented": "Implemented; mapping incomplete",
    "partial": "Partial",
    "planned": "Planned",
    "out_of_scope": "Intentionally excluded",
}


def escape_cell(value: object) -> str:
    return str(value or "—").replace("|", "\\|").replace("\n", " ")


def records() -> list[dict[str, str]]:
    data = json.loads(INTERFACE_MAP.read_text(encoding="utf-8"))
    if data.get("version") != 1:
        raise SystemExit(f"{INTERFACE_MAP}: unsupported interface-map version")
    by_symbol: dict[str, dict[str, str]] = {}
    for group in data["paths"]:
        for symbol, contract in group["symbols"].items():
            if symbol in LEGACY_MAC_HELPERS:
                continue
            candidate = {
                "area": group["path"],
                "symbol": symbol,
                "status": contract["status"],
                "mapping": contract.get("rust") or "",
                "reason": contract.get("reason") or "",
            }
            previous = by_symbol.get(symbol)
            if previous is None:
                by_symbol[symbol] = candidate
                continue
            comparable = ("status", "mapping", "reason")
            if any(previous[key] != candidate[key] for key in comparable):
                raise SystemExit(
                    f"{INTERFACE_MAP}: conflicting duplicate symbol {symbol}"
                )
            previous["area"] += f", {group['path']}"
    result = list(by_symbol.values())
    if len(result) != 218:
        raise SystemExit(
            f"{INTERFACE_MAP}: expected 218 pinned functions, found {len(result)}"
        )
    unknown = {row["status"] for row in result} - STATUS_LABELS.keys()
    if unknown:
        raise SystemExit(f"{INTERFACE_MAP}: unknown statuses: {sorted(unknown)}")
    return sorted(result, key=lambda row: (row["area"], row["symbol"]))


def render(rows: list[dict[str, str]]) -> str:
    counts = Counter(row["status"] for row in rows)
    lines = [
        "# FreeType 2.14.3 Function Support",
        "",
        "> **Authoritative generated contract:** do not edit this file directly.",
        "> Update `tests/data/interface_map.json`, then run",
        "> `python3 scripts/generate_support_matrix.py`.",
        "",
        "This is the application-adoption disposition of every function in the",
        "pinned FreeType 2.14.3 public-header inventory. It is not an export",
        "inventory or code-coverage report. A declaration, stub, null-validation",
        "route, or narrow success probe can exist without making a function",
        "application-ready. Only `Complete` rows claim a complete maintained",
        "mapping; every other status requires application-specific review.",
        "",
        "## 1. Summary",
        "",
        "| Status | Functions | Meaning |",
        "|---|---:|---|",
        f"| Complete | {counts['complete']} | Maintained application behavior and mapping are complete |",
        f"| Implemented; mapping incomplete | {counts['implemented']} | Runtime code exists; the application mapping is incomplete |",
        f"| Partial | {counts['partial']} | Only the documented behavior is ready |",
        f"| Planned | {counts['planned']} | No application-ready implementation is claimed |",
        f"| Intentionally excluded | {counts['out_of_scope']} | Outside the currently declared product surface |",
        f"| **Total** | **{len(rows)}** | Pinned public function inventory |",
        "",
        "## 2. Function inventory",
        "",
        "| Area | FreeType function | Status | Rust mapping | Boundary or reason |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| `{}` | `{}` | {} | {} | {} |".format(
                escape_cell(row["area"]),
                escape_cell(row["symbol"]),
                STATUS_LABELS[row["status"]],
                escape_cell(row["mapping"]),
                escape_cell(row["reason"]),
            )
        )
    lines.extend(
        [
            "",
            "## 3. Verification",
            "",
            "Run these commands from the repository root:",
            "",
            "```bash",
            "python3 scripts/generate_support_matrix.py --check",
            "make api-abi-audit",
            "python3 scripts/generate_support_matrix.py --check \\",
            "  --audit-json target/api-abi-audit/api_abi_audit.json",
            "```",
            "",
            "The second check proves that the committed adoption map covers the same",
            "218 symbols as the independently parsed pinned C header inventory.",
            "Runtime routes, exact parity cases, and the 12-category C contract are",
            "reported separately; they cannot promote a row implicitly.",
            "",
        ]
    )
    return "\n".join(lines)


def cross_check_audit(rows: list[dict[str, str]], path: Path) -> None:
    audit = json.loads(path.read_text(encoding="utf-8"))
    audit_rows = {row["symbol"]: row for row in audit["functions"]}
    mapped_rows = {row["symbol"]: row for row in rows}
    if set(audit_rows) != set(mapped_rows):
        missing = sorted(set(audit_rows) - set(mapped_rows))
        extra = sorted(set(mapped_rows) - set(audit_rows))
        raise SystemExit(
            f"support/audit symbol mismatch: missing={missing}, extra={extra}"
        )
    mismatches = []
    for symbol, row in mapped_rows.items():
        if row["status"] != audit_rows[symbol]["fontdone_status"]:
            mismatches.append(
                f"{symbol}: map={row['status']} audit={audit_rows[symbol]['fontdone_status']}"
            )
    if mismatches:
        raise SystemExit("support/audit status mismatch:\n" + "\n".join(mismatches))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--audit-json", type=Path)
    args = parser.parse_args()

    rows = records()
    if args.audit_json is not None:
        cross_check_audit(rows, args.audit_json)
    content = render(rows)
    stale = [
        output
        for output in OUTPUTS
        if not output.exists() or output.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if stale:
            for output in stale:
                print(f"stale generated support matrix: {output.relative_to(ROOT)}")
            raise SystemExit(1)
        print(f"support matrix: {len(rows)} pinned functions, generated files clean")
        return
    for output in OUTPUTS:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8")
        print(output.relative_to(ROOT))


if __name__ == "__main__":
    main()
